### ISSUE TITLE
export env variables from step to step.

### ISSUE THREAD

**Issue by DocBradfordSoftware** [GoogleCloudPlatform/cloud-builders#100]
I would like to have a single trigger select different clusters based upon the branch name.
The code below works, but it looks like a kludge.  Is there a more elegant way to pass environment variables from step to step?

```yaml
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  id: 'set-cluster'
  waitFor: ['-']
  args:
  - '-c'
  - |
    if [ "$BRANCH_NAME" = "develop" ]
    then
    echo "us-central1-f" > ZONE.txt
    echo "cluster-1" > CLUSTER.txt
    else
    echo "us-west1-a" > ZONE.txt
    echo "cluster-2" > CLUSTER.txt
    fi
    cat ZONE.txt
    cat CLUSTER.txt

- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export CLOUDSDK_COMPUTE_ZONE=`cat ZONE.txt`
    export CLOUDSDK_CONTAINER_CLUSTER=`cat CLUSTER.txt`
    /builder/kubectl.bash get ns
  waitFor: ['set-cluster']
```
