### ISSUE TITLE
gke-deploy timeout change from default 5mins

### ISSUE THREAD

**Issue by brijin-urolime** [GoogleCloudPlatform/cloud-builders#1031]
I used to deploy the new deployments to the cluster using cloudbuild with gke-deploy. 

Below is the deploy stage.

  - id: 'Deploy'
    name: 'gcr.io/cloud-builders/gke-deploy:stable'
    args:
      - 'run'
      - '--filename=$_K8S_YAML_PATH'
      - '--image=gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA'
      - '--label=$_K8S_LABELS,gcb-build-id=$BUILD_ID'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'

It was working fine. 

However, recently had to add some sidecars and dependencies to a particular microservice pod. As there are 4 pods of this microservice deployment running, for each new deployment, its causing the deploy time error. That deployment to the cluster works fine in the background, but to get acknowledgment once all pods are up is more than the gke-deploy timeout (5mins), it returns status as failed. 

I added timeout parameter in Deploy stage, Its not reflecting and still defaults to 5mins.
 
    name: 'gcr.io/cloud-builders/gke-deploy:stable'
>>timeout 600s
    args:

Anyways to increase this?  
Or I can build a custom image with this repo, but I couldn't find where exactly is the timeout configured. 
I expected the timeout to be specified with "rollout status" but couldn't find it.

Any help would be really great at this moment.

**Comment by brijin-urolime** [comment]
snippet

**Comment by M-r-A** [comment]
> Anyways to increase this?
```yaml
  - id: 'Deploy'
    name: 'gcr.io/cloud-builders/gke-deploy:stable'
    args:
      - 'run'
      - '--filename=$_K8S_YAML_PATH'
      - '--image=gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA'
      - '--label=$_K8S_LABELS,gcb-build-id=$BUILD_ID'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--timeout=20m0s'
```
