### ISSUE TITLE
variable substitution with unexpected tokenizations

### ISSUE THREAD

**Issue by skippy** [GoogleCloudPlatform/cloud-builders#12]
hey folks,

if I use the following step in my `cloudbuilder.yaml`, where I use '_' as the delimiter, the behavior is unexpected (and I would argue, incorrect)

### unexpected behavior

```yaml
- name: 'gcr.io/cloud-builders/docker'
  dir: 'app'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app.web:$BRANCH_NAME_$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/app.web:$BRANCH_NAME_latest', '.']
  id:   'build'
```
when the build is triggered, it runs the following command (as shown by the CLI and gui under build details): 
```
build -t gcr.io/my-project/app.web:598ccb22d52633474fa92a4290b627634749472e -t gcr.io/my-project/app.web:latest .
```
Notice how the `$BRANCH_NAME` does not exist, nor the `_` delimiter?

### correct behavior
if I use a `-` instead of an `_` as a delimiter, I get the expected behavior:
```yaml
- name: 'gcr.io/cloud-builders/docker'
  dir: 'app'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app.web:$BRANCH_NAME_$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/app.web:$BRANCH_NAME_latest', '.']
  id:   'build'
```
triggers the following build, correctly: 
```
build -t gcr.io/my-project/app.test-branch-ef5776bd22bd72d6599a7f9ece6e78523c597553 -t gcr.io/my-project/app.web:test-branch-latest .
```

### Summary
Tokenization of variables seems to be too greedy.  The expected behavior is it should only substitute the token, not anything else.  

let me know if you want additional information
