### ISSUE TITLE
[go] no such file or directory when trying to run built image

### ISSUE THREAD

**Issue by gelidus** [GoogleCloudPlatform/cloud-builders#122]
Hi, I am trying to build a container image from my cli tool, however, every time I want to start the built container, I get the error "no such file or directory". Hello world works ok for me, however, I have no idea what I am doing wrong with this one:

https://github.com/flowup/cloudfunc/blob/cloudbuilder/cloudbuild.yaml

```yaml
steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['get', './...']
  env: ['PROJECT_ROOT=cloudfunc']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=cloudfunc']
- name: 'gcr.io/cloud-builders/go'
  args: ['test', 'cloudfunc']
  env: ['PROJECT_ROOT=cloudfunc']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/cloudfunc', '.']
images: ['gcr.io/$PROJECT_ID/cloudfunc']
```
