### ISSUE TITLE
Add hooks fx. for status updates

### ISSUE THREAD

**Issue by tlbdk** [GoogleCloudPlatform/cloud-builders#127]
Right now you have to build a service/cloud function that listes to pub/sub to do full integration on build status, it would be nice if this could be done easily as part of the cloudbuild.yaml:

Fx. here we could have a github integration container that could update the github status based on the build steps:

``` yaml
steps:
  - name: 'gcr.io/cloud-builders/npm:current'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm:current'
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/test:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/test:latest', '.']
images: ['gcr.io/$PROJECT_ID/test:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/test:latest']
hooks:
  build_status:
     - name: 'gcr.io/cloud-builders/github'
        args: ['update-status', '$COMMIT_SHA', 'cloudbuilder/$BUILD_STEP', '$BUILD_STATUS', 'Build status is $BUILD_STATUS for $BUILD_STEP','$BUILD_LOGS_URL']
```
