### ISSUE TITLE
Cryptic error from gcloud kms command

### ISSUE THREAD

**Issue by charith-qubit** [GoogleCloudPlatform/cloud-builders#144]
I have a build configuration that decrypts a secret using KMS as the first step. Everything works perfectly when I run the build through `container-builder-local` but when run inside GCB, I get the following error message:

```
ERROR: (gcloud.kms.decrypt) INVALID_ARGUMENT: Decryption failed
```

Container builder service account has the "Cloud KMS CryptoKey Decrypter" role attached to it. One thing I noticed when trying to debug the issue is that the version of the gcloud container pulled by container builder is not the same as the one I have locally:

**Container builder**: `gcr.io/cloud-builders/gcloud@sha256:7db6edb77a55f63f2881ef21bf08eb7335f57b5f30cc1d4a83b7cace69cf4aa1`
**Local**: `gcr.io/cloud-builders/gcloud@sha256:8f4c285c2ced181762a36619a0625926289aac7fbce4edc4d2653e6678fba3e7`

I updated my build config to use the container version that works locally. However, the build still fails with the same error. 

```yaml
steps:
    - name: gcr.io/cloud-builders/gcloud@sha256:8f4c285c2ced181762a36619a0625926289aac7fbce4edc4d2653e6678fba3e7
      args:
          - --project=$PROJECT_ID
          - kms
          - decrypt
          - --ciphertext-file=/workspace/_build.tar.gz.enc
          - --plaintext-file=/credentials/_build.tar.gz
          - --location=global
          - --keyring=xxx-keyring
          - --key=xxx-key
```

I am a bit lost as it's impossible to recreate the problem locally and the remote error message is not very descriptive. Any thoughts on what could be causing this?
