### ISSUE TITLE
Persistence not working as expected

### ISSUE THREAD

**Issue by lypht** [GoogleCloudPlatform/cloud-builders#151]
**Issue:** Using a cloudbuild.yaml manifest, I am using an intermediate Dockerfile.build step to produce a binary I wish to consume in a subsequent build step.

**Expected result:** Persisted volume mounts and serves files between build steps.

**Actual result:**  The daemon in the subsequent step cannot stat the persisted file.

cloudbuild.yaml:
```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/random-project/build-image', '-f', 'Dockerfile.build', '.']
  volumes:
  - name: 'persistent-volume'
    path: '/tmp/persistent-directory'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/random-project/image-with-binary', '.']
  volumes:
  - name: 'persistent-volume'
    path: '/tmp/persistent-directory'
images: ['gcr.io/random-project/build-image', 'gcr.io/random-project/image-with-binary']
```

My build-image succeeds both in building locally and via Step 0 in the cloudbuild.yaml file above, and I'm able to run the binary locally from the correct path.  However when attempting Step 1 in the cloudbuild.yaml file, I receive the following error:
```
Step #1: Sending build context to Docker daemon 92.16kB

Step #1: Step 1/4 : FROM scratch
Step #1: ---> 
Step #1: Step 2/4 : ADD /tmp/persistent-directory/main /
Step #1: ADD failed: stat /var/lib/docker/tmp/docker-builder760679385/tmp/persistent-directory/main: no such file or directory
``` 

The Dockerfile to consume and serve the binary:
```
FROM scratch
ADD /tmp/persistent-directory/main /
EXPOSE 8080
CMD ["/main"]
```
Any insight would be greatly appreciated.
