### ISSUE TITLE
Proposal: Provide contract "go.{ash,bash} will be in PATH"

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-builders#16]
I just found myself doing this:

```yaml
steps:
- id: compile
  name: gcr.io/cloud-builders/go:alpine
  env: ["PROJECT_ROOT=myapp"]
  entrypoint: /bin/ash # we need this to do the $(git) substutiton below
  args:
  - '-c'
  - >
    /builder/go.ash install -v \
      -ldflags="-X myapp/version.version=$(git describe --always --dirty)" \
        ./myapp/main
```

Note that I'm referring to the program as `/bin/ash -c "/builder/go.ash ..."`. If somebody were to change that path, downstream users referring to go.ash with its full path will get broken.

**Proposal:** Add the directory containing `go.ash`/`go.bash` to PATH env var.

If folks agree, I can contribute a CL. @skelterjohn
