### ISSUE TITLE
Can't get .git directory to show up in remote builds

### ISSUE THREAD

**Issue by abevoelker** [GoogleCloudPlatform/cloud-builders#236]
I'm submitting a remote build with `gcloud container builds submit --config cloudbuild.yaml` and no matter what I try, the `.git` directory is not showing up in the temporary tarballs. My Dockerfile needs to access the `.git` directory for the build and obviously it can't find it and all my remote builds fail (local builds work fine).

There is no `.dockerignore`, no `.gitignore`, no `.gcloudignore`, and no "Some files were not included in the source upload." message like I get in other projects where I use those ignore files.

If I create a different hidden directory:

```
mkdir .foo
touch .foo/bar
```
that directory does show up in the tarball, so I know it's not excluding all hidden directories.

Is there some hardcoding specifically to exclude `.git` when creating the tarball?

**Comment by bendory** [comment]
Indeed, if you look at the [code for `gcloudignore`](https://github.com/google-cloud-sdk/google-cloud-sdk/blob/master/lib/googlecloudsdk/command_lib/util/gcloudignore.py), you'll see that we generally ignore a `.git` directory, since it is rather unusual to want to upload this as part of your build context.

If you want it, you have several options:
- create an empty `.gcloudignore` (`touch .gcloudignore`)
- create a `.gcloudignore` (or `.gitignore`) that ignores the files you don't want but doesn't ignore `.git`
- create a `.gcloudignore` that explicitly includes `.git` (`echo '!.git' > .gcloudignore`)
- turn off the ignore behavior completely: `gcloud config set gcloudignore/enabled false`

See the [gcloudignore documentation](https://cloud.google.com/sdk/gcloud/reference/topic/gcloudignore) for further details.

**Comment by abevoelker** [comment]
Thank you for the detailed reply, I got it working with your suggestions. :balloon: :tada: 

I agree it is rather unusual (I used to always add `.git` to `.dockerignore`), but I like making the git revision available to my web app for use in a certain admin panel (after that part of the build `.git` is deleted), e.g.

```
RUN \
  git rev-parse --verify HEAD > /var/www/.git-revision &&\
  rm -rf /var/www/.git
```

**Comment by grantstephens** [comment]
Cloud this please be documented somewhere. I can't find any reference to default `.gcloudignore` items in the docs

**Comment by bill-within** [comment]
@bendory is there a different logic applied when using the GCB GitHub App? I'm trying to get private submodules working, but the extracted tarball doesn't contain a .git folder

**Comment by bendory** [comment]
redirect to @wlynch

**Comment by tjanson** [comment]
I think it’s worth reopening this issue. I appreciate the thorough answer, @bendory, but it seems the `.gcloudignore` isn’t used when builds are triggered from GitHub.

Or is there a separate issue tracking that in particular?

**Comment by JohnPaton** [comment]
I'm also running into this: with the `.git` directory is not being added to my image in Cloud Build triggered by GitHub, despite having an empty `.gcloudignore` present.

**Comment by saminiemi** [comment]
If found it will work with GitHub this way: 

- First connect your GitHub repository to Cloud Source Repositories (https://https://source.cloud.google.com/)
- Add GitHub repository as an external repository
- Create Build Trigger agains mirrored repository

In this way there is .git folder available in workdir during the build process (still need include it on .gcloudignore)

**Comment by JohnPaton** [comment]
The following build step fetches the `.git` directory as long as your build has access to your repo:

```yaml
  - id: Get the .git directory
    name: eu.gcr.io/cw-dev-ds-0001/builders/git/master
    args:
      - bash
      - -c
      - |-
        # get the .git directory only
        git clone --no-checkout --branch $BRANCH_NAME git@github.com:<USER_NAME>/$REPO_NAME /tmp/repo ;
        # move it to the workspace
        mv /tmp/repo/.git .
```

**Comment by mr-smithers-excellent** [comment]
Also experiencing this issue with the new Cloud Build GitHub App triggers.  Have attempted to explicitly add `!.git` to the `.gcloudignore` file with no success.

@bendory @wlynch - have you been able to recreate this on your end?

**Comment by Redgwell** [comment]
@saminiemi Your workaround doesn't work if you want to take advantage of the "Build on PR" feature that's only available with the Cloud Build GitHub App repo :(

**Comment by tlbdk** [comment]
We do this instead of moving the repo:

``` yaml
  # checkout git submodules
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      git init
      git remote add origin git@github.com:/orgname/$REPO_NAME.git
      git fetch --depth=1 origin $COMMIT_SHA
      git reset --hard FETCH_HEAD
      git config -f .gitmodules submodule.core.url git@github.com:/orgname/$REPO_NAME.git
      git submodule update --init
```

And for authentication we use this project:
https://github.com/connectedcars/auth-wrapper

**Comment by Datamance** [comment]
Hi all,

There's a much quicker (still hacky) way to get the .git folder in without having to download the entire world all over again:

```yaml
- id: get-git-history
  name: gcr.io/cloud-builders/git
  entrypoint: bash
  args:
    - '-c'
    - |
      git clone https://github.com/lookit/lookit-api.git --no-checkout
      mv lookit-api/.git .
      git fetch --unshallow
      rm -rf lookit-api
```

Basically, use `--no-checkout` to only get the `.git` folder, then move it up one level, then delete the unnecessary checkout folder.

**Comment by matthias-baetens** [comment]
Another alternative is using Google Cloud Secret Manager - put your GitHub OAuth token and retrieve in the Cloud Build image:

Adding secret:
`
echo $GITHUB_TOKEN | gcloud secrets create github-token --data-file=- --replication-policy=automatic
`

Retrieving secret in Build pipeline:
'
GITHUB_TOKEN=$(gcloud secrets versions access latest --secret=$GITHUB_SECRET_NAME)
'

**Comment by matthiasa4** [comment]
Another alternative is using Google Cloud Secret Manager - put your GitHub OAuth token and retrieve in the Cloud Build image:

Adding secret:
```
echo $GITHUB_TOKEN | gcloud secrets create github-token --data-file=- --replication-policy=automatic
```

Retrieving secret in Build pipeline:
```
GITHUB_TOKEN=$(gcloud secrets versions access latest --secret=$GITHUB_SECRET_NAME)
COMMAND=$(echo 'git clone https://GITHUB_TOKEN@github.com/ORGANISATION/REPOSITORY' | sed -e "s/GITHUB_TOKEN/$GITHUB_TOKEN/" )
eval $COMMAND
```

**Comment by mrmeku** [comment]
Here's a solution that you can use without having to authenticate with Github:

First connect your GitHub repository to Cloud Source Repositories (https://https://source.cloud.google.com/)

Then use the gcloud builder to auth against your cloud source repo:
```
- name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
      - git init
      - git config credential.helper "!gcloud auth git-helper --account=<SERVICE-ACCOUNT-EMAIL> --ignore-unknown $@"
      - git remote add origin https://source.developers.google.com/p/<CLOUD_SOURCE_REPOSITORIES_PATH>
```

Note that the value for SERVICE-ACCOUNT-EMAIL can be found under https://console.cloud.google.com/cloud-build/settings/service-account

Good luck everyone!
