### ISSUE TITLE
Pulling custom cloud builder slows down builds

### ISSUE THREAD

**Issue by cbuchacher** [GoogleCloudPlatform/cloud-builders#266]
I have a cloudbuild.yaml with about 70 lines worth of custom build steps. I do this in order to [access private Github repositories](https://cloud.google.com/container-builder/docs/access-private-github-repos), and to push images to computed locations. Currently I use the same cloudbuild.yaml and supplementary files in about 20 repositories. I have created a custom builder image in order to remove the duplication. But, while the pre-defined cloud builders are available right away, in each build it takes about 1-2 minutes of additional build time to pull the custom builder from gcr.io.

Is there any way to avoid both the slow-down and the duplication?

**Comment by cbuchacher** [comment]
I thought about downloading and executing the build script to a bucket like this:

```yaml
steps:
- name: gcr.io/cloud-builder/git
  entrypoint: bash
  args:
  - -c
  - |
    gsutil cp gs://my-cloud-builder/git-step.sh ./ &&
    ./git-step.sh
- name: gcr.io/cloud-builder/docker
  entrypoint: bash
  args:
  - -c
  - |
    gsutil cp gs://my-cloud-builder/docker-step.sh ./ &&
    ./docker-step.sh
```

If I could summarize the git and docker steps into one, that would be a great help, though. Could we add an `everything` cloud-builder which would contain all the frequently needed tools (including git and docker)?
