### ISSUE TITLE
Bootstrapping --cache-from

### ISSUE THREAD

**Issue by lostman** [GoogleCloudPlatform/cloud-builders#277]
I have tried setting up caching for my build using `--cache-from` as described in the docs:

```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/latest-image']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--cache-from',
            'gcr.io/$PROJECT_ID/latest-image',
            '-t', 'gcr.io/$PROJECT_ID/latest-image',
            '.'
        ]
images: ['gcr.io/$PROJECT_ID/latest-image']
```

However, the `pull` step fails if the image doesn't exist:

```
BUILD
Starting Step #0
Step #0: Already have image (with digest): gcr.io/cloud-builders/docker
Step #0: Using default tag: latest
Step #0: Error response from daemon: manifest for gcr.io/$PROJECT_ID/latest-image:latest not found
Finished Step #0
```

This makes my `cloudbuild.yaml` not very declarative. I have to comment out all `--cache-from` steps if I remove any of the cached images from the registry.

Is there a way to make it work? Perhaps by marking some build steps as "allowed to fail"?

**Comment by Philmod** [comment]
Hey Maciej,

You could use bash in the first step: 
```
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/latest-image || exit 0
```
