### ISSUE TITLE
Container Builder is ignoring env variables

### ISSUE THREAD

**Issue by nerdyglasses** [GoogleCloudPlatform/cloud-builders#28]
Hey I really like the idea to have container builder available.

For some reason it doesn't work for us atm, though.

We have a cloudbuild.yaml like that:
```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-project', '.']
  env:
  - 'RAILS_ENV=staging'
  - 'SECRET_KEY_BASE=abc'
  - 'ASSETS_PROVIDER=Google'
  - 'GOOGLE_STORAGE_ACCESS_KEY=MY'
  - 'GOOGLE_STORAGE_SECRET_KEY=KEY'
images:
- 'gcr.io/$PROJECT_ID/my-project'
timeout: '1200s'
```

But for some reason it's not using the `env` variables.

![container_registry_-_boxes](https://cloud.githubusercontent.com/assets/449438/24219384/e144639c-0f46-11e7-8fe0-7aafddff8926.png)

Did I do a mistake or is that a beta bug?
