### ISSUE TITLE
kubectl image ignores env.CLOUDSDK_CONTAINER_CLUSTER when used in multiple steps

### ISSUE THREAD

**Issue by yungchin** [GoogleCloudPlatform/cloud-builders#290]
This may be one of those "don't do that, then" bugs, but just in case it's helpful: if you interact with multiple GKE clusters during the same build, like so

```
  - name: gcr.io/cloud-builders/kubectl
    args: ['create', '-f', 'this.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster'
  - name: gcr.io/cloud-builders/kubectl
    args: ['create', '-f', 'that.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-other-cluster'
```

then I currently find that `that.yaml` is deployed to `my-first-cluster` instead of `my-other-cluster`.

**Comment by ebrake** [comment]
I am also facing this issue: Updating CLOUDSDK_CONTAINER_CLUSTER does not get applied with multiple steps.

**Comment by Philmod** [comment]
Hey!

I made a quick test, and the environment variables seem to work as expected: 
```
steps:
- name: gcr.io/cloud-builders/kubectl
  entrypoint: 'bash'
  args: ['-c', 'echo hello $$CLOUDSDK_CONTAINER_CLUSTER']
  env:
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster'
- name: gcr.io/cloud-builders/kubectl
  entrypoint: 'bash'
  args: ['-c', 'echo hello $$CLOUDSDK_CONTAINER_CLUSTER']
  env:
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-other-cluster'
```

Logs: 
```
Starting Step #0
Step #0: Already have image (with digest): gcr.io/cloud-builders/kubectl
Step #0: hello my-first-cluster
Finished Step #0
Starting Step #1
Step #1: Already have image (with digest): gcr.io/cloud-builders/kubectl
Step #1: hello my-other-cluster
Finished Step #1
```

**Comment by ebrake** [comment]
@Philmod Hm! Are you able to run commands against the cluster after the environment is updated? I am attempting to set an image for kubernetes in a separate cluster, but the initial CLOUDSDK_CONTAINER_CLUSTER is still being used.

**Comment by Philmod** [comment]
I am now wondering if the state is kept globally (i.e. across steps) because of this [line](https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/kubectl/kubectl.bash#L4)... cc @skelterjohn

**Comment by stevencorona** [comment]
Had this same issue— the kubeconfig file gets written to the cloud build workspace directory the first time get-credentials is called and then it skips on subsequent calls. I solved it by setting `KUBECONFIG` in the subsequent steps env, i.e:

```
steps:
- name: gcr.io/cloud-builders/kubectl
  entrypoint: 'bash'
  args: ['-c', 'echo hello $$CLOUDSDK_CONTAINER_CLUSTER']
  env:
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster'
- name: gcr.io/cloud-builders/kubectl
  entrypoint: 'bash'
  args: ['-c', 'echo hello $$CLOUDSDK_CONTAINER_CLUSTER']
  env:
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-other-cluster'
    - 'KUBECONFIG=/workspace/othercluster-kubeconfig'
```

**Comment by ebrake** [comment]
@stevencorona Decent!!

**Comment by rajatvig** [comment]
This issue can be closed now as it is fixed.

**Comment by mercuriete** [comment]
reopen because this was reverted

**Comment by ImJasonH** [comment]
Confirming this is reproducible:

In a project with two clusters:

```
 steps:
 - name: gcr.io/cloud-builders/kubectl
   env:
   - CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1
   - CLOUDSDK_COMPUTE_ZONE=<zone>
   args: ['get', 'namespaces']
 - name: gcr.io/cloud-builders/kubectl
   env:
   - CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-2
   - CLOUDSDK_COMPUTE_ZONE=<zone>
   args: ['get', 'namespaces']
```

`gcloud builds submit --no-source` succeeds, but only lists namespaces in the first cluster; the second step doesn't re-get credentials for that cluster, so it lists the first cluster's namespaces again.
