### ISSUE TITLE
Possibility to ignore step failure

### ISSUE THREAD

**Issue by edevil** [GoogleCloudPlatform/cloud-builders#294]
In order to speed up my CI/CD pipeline I try to fetch the previous version of my docker container in order to build with "--cache-from". However, the first time the pipeline is run there is no previous image and the docker pull cloud builder step fails.

Is there a way to ignore a step failure? I wouldn't want to have to alter the builder script just for the first time the pipeline runs.

**Comment by edevil** [comment]
I managed to solve it based on #295 
```
- name: 'gcr.io/cloud-builders/docker'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/${REPO_NAME}:${BRANCH_NAME/\//_}_latest || true']
  entrypoint: '/bin/bash'
  env:
    - 'BRANCH_NAME=${BRANCH_NAME}'
```
