### ISSUE TITLE
Alter build variable at runtime

### ISSUE THREAD

**Issue by edevil** [GoogleCloudPlatform/cloud-builders#295]
My build pipeline builds a docker image and I want it to have a tag like "BRANCH_SHORTHASH".

In Travis I do it like this:
```
- IMAGE_TAG="${TRAVIS_BRANCH/\//_}.${TRAVIS_COMMIT::8}"
```

Notice the substitution on the branch name, because I need branches with names like "feature/xpto" to be changed to "feature_xpto", the / character is not valid in a tag name.

Is this possible in google cloud builder?

**Comment by bendory** [comment]
We don't have first-class support for this, but can do it using the bash shell. For some examples, try running this build by pasting it into a `subst.yaml` and running `gcloud container builds submit --config=subst.yaml --no-source`:

```
steps:
- name: 'ubuntu'
  args: [ "bash", "-c", "echo BUILD_ID is ${BUILD_ID}" ]
- name: 'ubuntu'
  args: [ "bash", "-c", "echo When FOO=${BUILD_ID}, FOO:10 resolves to ${FOO:10}" ]
  env: 'FOO=${BUILD_ID}'
- name: 'ubuntu'
  args: [ "bash", "-c", "echo BUILD_ID:10 resolves to ${BUILD_ID:10}" ]
- name: 'ubuntu'
  args: [ "bash", "-c", "echo expr $BUILD_ID 10 14 resolves to $$(expr substr $BUILD_ID 10 14)" ]
- name: 'ubuntu'
  args: [ "bash", "-c", "echo When FOO=${BUILD_ID}, envvar FOO resolves to $$FOO" ]
  env: 'FOO=${BUILD_ID}'
```

If you want the value of such a string manipulation to become a tag name, you can either run your `docker build` inside a bash command or have one build step create a bash script (which calls `docker build --tag...`) that is then executed by a subsequent build step. So, for example this config file would tag `my-image` with a tag based on the 10th-through-last characters of the `$BUILD_ID`:

```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ "-c", "docker build -t gcr.io/$PROJECT_ID/my-image:${FOO:10} ." ]
  entrypoint: '/bin/bash'
  env: "FOO=${BUILD_ID}"
```

Note that the above means that you can't use the `images` field to push your image. Instead, push the image yourself in a subsequent build step:

```
- name: 'gcr.io/cloud-builders/docker'
  args: [ "-c", "docker push gcr.io/$PROJECT_ID/my-image:${FOO:10}" ]
  entrypoint: '/bin/bash'
  env: "FOO=${BUILD_ID}"
```
