### ISSUE TITLE
using a package manager you need to go get, e.g. glide

### ISSUE THREAD

**Issue by errordeveloper** [GoogleCloudPlatform/cloud-builders#3]
I've ended-up writing the following and it took me a few hours to figure out.
```YAML
steps:

- name: 'gcr.io/cloud-builders/go'
  env: ['PROJECT_ROOT=github.com/errordeveloper/kubegen']
  args: ['get', 'github.com/Masterminds/glide']

- name: 'gcr.io/cloud-builders/golang-project'
  env: ['PROJECT_ROOT=github.com/errordeveloper/kubegen']
  args: ['github.com/Masterminds/glide', '--base-image=gcr.io/cloud-builders/golang-project', '--tag=builder-with-glide']

- name: 'builder-with-glide'
  env: ['PROJECT_ROOT=github.com/errordeveloper/kubegen']
  args: ['-c', 'source /builder/prepare_workspace.inc && prepare_workspace && cd ./gopath/src/github.com/errordeveloper/kubegen && glide up --strip-vendor']
  entrypoint: '/bin/sh'

- name: 'gcr.io/cloud-builders/golang-project'
  env: ['PROJECT_ROOT=github.com/errordeveloper/kubegen']
  args: ['github.com/errordeveloper/kubegen/cmd/kubegen', '--base-image=scratch', '--tag=gcr.io/$PROJECT_ID/kubegen']

images: ['gcr.io/$PROJECT_ID/kubegen']
```
I'm not entirely happy about how it looks/works right now, but may be we could discuss some improvements and upstream this somehow or at least document it?

**Comment by skelterjohn** [comment]
That looks like a lot of work! I'm sure we can add glide to the existing
toolchain in a nice way, and I'll leave this open as a feature request. We
appreciate your interest.

**Comment by errordeveloper** [comment]
@skelterjohn thanks!

I've update the code with the latest version, and actually it turns out that I still need to hack around making `ve ndor/` work...

**Comment by errordeveloper** [comment]
Still no luck, see `cloudbuild` branch in `github.com/errordeveloper/kubegen` if you wanna try it.

**Comment by errordeveloper** [comment]
I think I'd have more luck if I just wrote `Dockerfile` and used that instead of Go builders, but I thought these builders would be somewhat better...

**Comment by skelterjohn** [comment]
I've put something in gcr.io/cloud-builders-testing/glide - can you see if it works for you?

**Comment by skelterjohn** [comment]
Ok, now I've got a basic example working... in a directory with this Dockerfile and cloudbuild.yaml, 'gcloud container builds submit --config cloudbuild.yaml .' short work nicely. It uses a glide build step to rebuild glide itself, with a 'glide install' step before compiling any go. Let me know what you think!

===Dockerfile===
FROM ubuntu

COPY glide/gopath/bin/glide /bin/glide

ENTRYPOINT ['/bin/glide']

===cloudbuild.yaml===
steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/Masterminds/glide']
- name: 'gcr.io/cloud-builders-testing/glide'
  dir: 'glide'
  env: ['PROJECT_ROOT=github.com/Masterminds/glide']
  args: ['install']
- name: 'gcr.io/cloud-builders/go'
  dir: 'glide'
  env: ['PROJECT_ROOT=github.com/Masterminds/glide']
  args: ['install', 'github.com/Masterminds/glide']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/build-glide', '.']
images: ['gcr.io/$PROJECT_ID/build-glide']

**Comment by errordeveloper** [comment]
Great! It looks like `gcr.io/cloud-builders/go` works now, but `gcr.io/cloud-builders/golang-project` still fails to find dependencies in `vendor/` for some reason. I suppose you have fixed underlying issue in go builder and golang-project builder is just waiting to be fix, but for the record, here is what I did. I'm happy to no use golang-project and provide Dockerfile instead, just reporting this in case you weren't aware.

```YAML
steps:

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/errordeveloper/kubegen']

- name: 'gcr.io/cloud-builders-testing/glide'
  env: ['PROJECT_ROOT=github.com/errordeveloper/kubegen']
  dir: 'kubegen'
  args: ['up', '--strip-vendor']

# this works:
- name: 'gcr.io/cloud-builders/go'
  env: ['PROJECT_ROOT=github.com/errordeveloper/kubegen', 'CGO_ENABLED=0']
  dir: 'kubegen'
  args: ['install', 'github.com/errordeveloper/kubegen/cmd/kubegen']

# but this doesn't work:
#- name: 'gcr.io/cloud-builders/golang-project'
#  env: ['PROJECT_ROOT=github.com/errordeveloper/kubegen', 'CGO_ENABLED=0']
#  dir: 'kubegen'
#  args: ['github.com/errordeveloper/kubegen/cmd/kubegen', '--base-image=scratch', '--tag=gcr.io/$PROJECT_ID/kubegen']

#images: ['gcr.io/$PROJECT_ID/kubegen']
```
