### ISSUE TITLE
Error when trying to run builds in parralel in the go image, workspace file exists

### ISSUE THREAD

**Issue by mogthesprog** [GoogleCloudPlatform/cloud-builders#31]
Hey guys, not sure if i'm posting this to the wrong project btw,

I have an issue running builds in parallel in the go build image. It tries to shadow link the workspace directory but since there are two builds in parallel, it seems that the directory already exists.

cloudbuilder.yaml
```
steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['get', 'github.com/tools/godep']
    env: ['PROJECT_ROOT=authproxy']
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'gopath/bin/godep'
    args: ['restore']
    env: ['PROJECT_ROOT=authproxy']
    id: 'go-restore'
  - name: 'gcr.io/cloud-builders/go'
    env: ['PROJECT_ROOT=authproxy']
    args: ['tool', 'vet', '.']
    waitFor: ['go-restore']
  - name: 'gcr.io/cloud-builders/go'
    env: ['PROJECT_ROOT=authproxy']
    args: ['tool', 'vet', '-shadowstrict', '.']
    waitFor: ['go-restore']
```

`logs`
```
starting build "3ffb769c-04d5-418e-9304-251075dbcf12"

FETCHSOURCE
Initialized empty Git repository in /workspace/.git/
From https://source.developers.google.com/p/dragon-creative/r/github-mogthesprog-authproxy
* branch 1692cc4909e860aeed3e494928358639682bf60b -> FETCH_HEAD
HEAD is now at 1692cc4 wip
BUILD
Step #0: Already have image (with digest): gcr.io/cloud-builders/go
Starting Step #0
Step #0: Creating shadow workspace and symlinking source into "./gopath/src/authproxy".
Step #0: Documentation at https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/go/README.md
Step #0: Running: go get github.com/tools/godep
Finished Step #0
Step #1 - "go-restore": Already have image (with digest): gcr.io/cloud-builders/go
Starting Step #1 - "go-restore"
Step #1 - "go-restore": godep: [WARNING]: godep should only be used inside a valid go package directory and
Step #1 - "go-restore": godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
Step #1 - "go-restore": godep: [WARNING]:	Current Directory: /workspace
Step #1 - "go-restore": godep: [WARNING]:	$GOPATH: 
Finished Step #1 - "go-restore"
Step #2: Already have image (with digest): gcr.io/cloud-builders/go
Starting Step #2
Step #3: Already have image (with digest): gcr.io/cloud-builders/go
Starting Step #3
Step #2: Creating shadow workspace and symlinking source into "./gopath/src/authproxy".
Step #2: Documentation at https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/go/README.md
Step #2: Running: go tool vet .
Step #3: Creating shadow workspace and symlinking source into "./gopath/src/authproxy".
Step #3: ln: ./gopath/src/authproxy/workspace: File exists
Finished Step #3
ERROR
ERROR: build step "gcr.io/cloud-builders/go@sha256:fd73433f7cb47df8712bab4ba95c5c4d98877fbab39a8155f333544d9c27652a" failed: exit status 1
```

It's likely something i've done wrong in the cloudbuilder yaml file since i'm still pretty new to this.
