### ISSUE TITLE
Using secretEnv with curl builder

### ISSUE THREAD

**Issue by nodesocket** [GoogleCloudPlatform/cloud-builders#312]
How can I reference a `secretEnv` in the `curl` cloud builder? I tried `$$API_SECRET_KEY` but this does not seem to work.

Here is a full example:

```
steps:
- name: gcr.io/cloud-builders/curl
  args: ['--silent', '--location', '-u', 'user:$$API_SECRET_KEY', 'https://api.mydomain.io/create']
  secretEnv: ['API_SECRET_KEY']

secrets:
- kmsKeyName: projects/project-id-here/locations/global/keyRings/cloud-build/cryptoKeys/key
  secretEnv:
    API_SECRET_KEY: long-base64-value-here
```

**Comment by ImJasonH** [comment]
To reference an env variable in a command, you need to invoke a shell:

```yaml
steps:
- name: gcr.io/cloud-builders/curl
  entrypoint: bash
  args: ['-c', 'curl --silent --ocation -u user:$$API_SECRET_KEY https://api.mydomain.io/create']
```

Let me know if that doesn't work. Our documentation can do a better job of documenting this.
