### ISSUE TITLE
Kubectl does not support 'set image cronjob'

### ISSUE THREAD

**Issue by b3ntly** [GoogleCloudPlatform/cloud-builders#313]
The following command which runs normally using kubectl on my development machines returns the following error in cloud-builder:

```yaml
- name: gcr.io/cloud-builders/kubectl
  args: ['set', 'image', 'cronjob/mturkjobtest', '${_name}=gcr.io/${_projectid}/${container}:$COMMIT_SHA']
  env: ['CLOUDSDK_COMPUTE_ZONE=us-west1-a', 'CLOUDSDK_CONTAINER_CLUSTER=${_cluster}']   
```

and the accompanying error message:

```bash
error: cronjobs/${_name} the object is not a pod or does not have a pod template
```

For clarity no substitution variables are actually being used in my cloudbuilder.yaml, I just wanted to hide production variable names when created this issue.

Is this a problem with the kubectl cloud-builder tool being out of date? What's the best way to fix this for my build? It's kind of a big deal to keep my cronjobs updated with the latest builds.

**Comment by leejones** [comment]
It looks like the cloud builder version of `kubectl` is `1.9`:

```
$> docker run --rm --entrypoint kubectl gcr.io/cloud-builders/gcloud version --client
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

However, being able to run `kubectl set image` on a `cronjob` resource wasn't added until `1.10`: https://github.com/kubernetes/kubernetes/pull/57742.

**Comment by bendory** [comment]
Our `kubectl` build step is based on the `kubectl` version installed by `gcloud`; see the `Dockerfile`: https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/kubectl/Dockerfile

I don't know why `gcloud` installs 1.9.7 rather than 1.10+?

```
~$ gcloud components install kubectl


Your current Cloud SDK version is: 209.0.0
Installing components from version: 209.0.0

┌──────────────────────────────────────────────────────────────────┐
│               These components will be installed.                │
├─────────────────────┬─────────────────────┬──────────────────────┤
│         Name        │       Version       │         Size         │
├─────────────────────┼─────────────────────┼──────────────────────┤
│ kubectl             │                     │                      │
│ kubectl             │               1.9.7 │             14.9 MiB │
└─────────────────────┴─────────────────────┴──────────────────────┘

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Do you want to continue (Y/n)? 
```

**Comment by bendory** [comment]
@ImJasonH just gave me an explanation.

`gcloud` can only ship one `kubectl` binary, and that binary is always chosen to match the default version of GKE. `kubectl` only supports one version skew vs. the Kubernetes server.

So from the `cloud-builders` point-of-view, this is some combination of "works as intended" and "somebody else's problem", though that of course is both unhelpful and doesn't unblock you.

I think that one immediate reasonable way for you to get unblocked is to have support for `kubectl` at specific versions in our [Community Builders](http://github.com/GoogleCloudPlatform/cloud-builders-community) repo. I'm going to poke around and see if someone might want to provide that...

**Comment by bendory** [comment]
You could do that, but no need to use the docker cloud-builder; instead, just use the custom kubectl as your build step:

```
- name: me/image-with-custom-kubectl-version
  args: [ '-v', ... ]
```

**Comment by b3ntly** [comment]
Great! Final question, how does cloud-builder authorize build steps to use services like GKE? Is there a serviceaccount.json that I can map to said container? If so where on the build instance's filesystem is it located?

**Comment by bendory** [comment]
@b3ntly see:
- https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials
- https://cloud.google.com/cloud-build/docs/securing-builds/set-service-account-permissions

The [kubectl examples](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/kubectl) may also prove helpful.

**Comment by ImJasonH** [comment]
@b3ntly GCB automatically injects credentials for your project's [builder service account](https://cloud.google.com/cloud-build/docs/securing-builds/set-service-account-permissions#what_is_the_product_name_short_service_account) in such a way that `gcloud` and other tools that understand [Application Default Credentials](https://cloud.google.com/docs/authentication/production) can use.

**Comment by seans3** [comment]
More info on creating multiple kubectl Docker images. I believe you can create Docker images of specific versions of kubectl with the following example Dockerfile commands (NOTE: kubectl 1.10):

# Ensure wget and chmod are installed into the image
CMD wget https://storage.googleapis.com/kubernetes-release/release/v1.10.2/bin/linux/amd64/kubectl
CMD chmod +x kubectl
ADD kubectl /usr/local/bin/kubectl
ENTRYPOINT ["/usr/local/bin/kubectl"]

Full disclosure: I haven't tried this yet.

Build within Dockerfile directory: docker build -t kubectl-1.10 .

**Comment by grunde73** [comment]
Hi,
We are running cron jobs on GKE and wanted to use GCP build triggers to update job images automatically with commits to GitHub. When setting up this I ran into the problem with `kubectl` in `cloud-builders` being version 1.9 (our GKE cluster is running Kubernetes 1.10.6).

After fiddling around a bit I managed to build and use my own cloud-builders/kubectl image and use that to set the new image for the cron job (using bits and pieces from this thread).

Here is what is working for me:
* The build trigger set and injects the variables `_CLOUDSDK_COMPUTE_ZONE`, and `_CLOUDSDK_CONTAINER_CLUSTER` into the kubectl job (must match your deployment).

* cloudbuild.yaml in target repo
```yaml
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME-image:$SHORT_SHA', '--tag', 'latest', '.' ]
    
    - name: 'gcr.io/$PROJECT_ID/kubectl:1.10'
    # - name: 'gcr.io/cloud-builders/kubectl'
    # Uncomment line above (and comment out line with kubectl:1.10) to revert to Google Cloud Builders version of kubectl
      args:
      - set
      - image
      - cronjobs/jobname
      - jobname=eu.gcr.io/$PROJECT_ID/$REPO_NAME-image:$SHORT_SHA
      env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'

images:
    - 'eu.gcr.io/$PROJECT_ID/$REPO_NAME-image:$SHORT_SHA'
```

To build the 'gcr.io/$PROJECT_ID/kubectl:1.10' image cloned https://github.com/GoogleCloudPlatform/cloud-builders/ and did the following changes

* Docerfile
```
FROM gcr.io/cloud-builders/gcloud
COPY kubectl.bash /builder/kubectl.bash
CMD wget https://storage.googleapis.com/kubernetes-release/release/v1.10.6/bin/linux/amd64/kubectl
CMD chmod +x kubectl
COPY kubectl /builder/kubectl
ENTRYPOINT ["/builder/kubectl.bash"]
```

* kubectl.bash, last line changed to:
```
/builder/kubectl "$@"
```
* cloudbuild.yaml
```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/kubectl:1.10', '.']

images:
  ['eu.gcr.io/$PROJECT_ID/kubectl:1.10']
```

Hope someone finds this useful, and that we can soon revert to using vanilla cloud-builders kubectl
