### ISSUE TITLE
steps: selectively run or skip steps depending on the status of the job

### ISSUE THREAD

**Issue by mbana** [GoogleCloudPlatform/cloud-builders#320]
Is there an option to do https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute, e.g.,

```yaml
  - run:
      name: Upload Failed Tests
      command: curl --data fail_tests.log http://example.com/error_logs
      when: on_fail
```
