### ISSUE TITLE
docker: cannot ping detached service in another step

### ISSUE THREAD

**Issue by mbana** [GoogleCloudPlatform/cloud-builders#321]
Hi, please see below config.
I cannot seem to reach the services started in the `docker-compose` step.
Thanks,

**cloudbuild.yaml:**

```yaml
steps:
- name: 'docker/compose:1.15.0'
  args: ['up', '-d','redis', 'mongo']
- name: 'docker/compose:1.15.0'
  args: ['ps']

- name: 'alpine'
  args: ['sh', '-c', 'while ! nc -v -z localhost 27017; do echo -e "\033[92m  ---> waiting for mongo ... \033[0m"; sleep 1; done']
```

**docker-compose.yml:**

```yaml
version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    # networks:
    #   - some_network
    ports:
      - 6379:6379

  mongo:
    image: mongo:3.6-jessie
    container_name: mongo
    hostname: mongo
    # networks:
    #   - some_network
    ports:
      - 27017:27017

# networks:
#   some_network:
```

**Output:**

```sh
$  cloud-build-local --config=cloudbuild.yaml --dryrun=false .
2018/08/06 13:06:23 Warning: there are left over step containers from a previous build, cleaning them.
2018/08/06 13:06:25 Warning: a network is left over from a previous build, cleaning it.
2018/08/06 13:06:25 Warning: there are left over step volumes from a previous build, cleaning it.
2018/08/06 13:06:29 Warning: The server docker version installed (18.06.0-ce-rc3) is different from the one used in GCB (17.12.0-ce)
2018/08/06 13:06:29 Warning: The client docker version installed (18.06.0-ce-rc3) is different from the one used in GCB (17.12.0-ce)
Using default tag: latest
latest: Pulling from cloud-builders/metadata
Digest: sha256:1a4ae9cbfeb9eb982c8788f1db42f80555499000cd1ce5dbfe657af9955f8812
Status: Image is up to date for gcr.io/cloud-builders/metadata:latest
2018/08/06 13:06:40 Started spoofed metadata server
2018/08/06 13:06:40 Build id = localbuild_6608e461-da7a-4684-9860-e5d5141f62c3
2018/08/06 13:06:40 status changed to "BUILD"
BUILD
Starting Step #0
Step #0: Already have image (with digest): docker/compose:1.15.0
Step #0: Recreating redis ... 
Step #0: Recreating mongo ... 
Step #0: Recreating redis
Recreating mongo ... done
Recreating redis ... done
Step #0: 
Finished Step #0
Starting Step #1
Step #1: Already have image (with digest): docker/compose:1.15.0
Step #1: Name               Command               State            Ports           
Step #1: -------------------------------------------------------------------------
Step #1: mongo   docker-entrypoint.sh mongod      Up      0.0.0.0:27017->27017/tcp 
Step #1: redis   docker-entrypoint.sh redis ...   Up      0.0.0.0:6379->6379/tcp   
Finished Step #1
Starting Step #2
Step #2: Already have image (with digest): alpine
Step #2:   ---> waiting for mongo ... 
Step #2:   ---> waiting for mongo ... 
Step #2:   ---> waiting for mongo ... 
Step #2:   ---> waiting for mongo ... 
Step #2:   ---> waiting for mongo ... 
Step #2:   ---> waiting for mongo ... 
^Cmake: *** [ci] Interrupt: 2
```
