### ISSUE TITLE
[go] The go tool ./... pattern will match /workspace/gopath and make the command fail

### ISSUE THREAD

**Issue by anr** [GoogleCloudPlatform/cloud-builders#324]
Summary: the go tool pattern `./...` is very convenient (eg to run all tests), but because the `gopath` directory is created inside the repo (and there's a link back), it apparently is tricky to use.

I was experimenting with the following cloudbuild.yaml:

```yaml
steps:
  - name: gcr.io/cloud-builders/go
    args: ['get', './...']
    env:  ['PROJECT_ROOT=${REPO_NAME}']

  - name: gcr.io/cloud-builders/go
    args: ['test', './...']
    env:  ['PROJECT_ROOT=${REPO_NAME}']
```

where REPO_NAME is `github.com/anr/moai`.

Unfortunately, because the pattern will match the `gopath` dir (and there's a link inside gopath back to the repo), I get errors such as:

```
Step #1: can't load package: package github.com/anr/moai/gopath/src/google.golang.org/genproto/googleapis/cloud/dataproc/v1: code in directory /workspace/gopath/src/github.com/anr/moai/gopath/src/google.golang.org/genproto/googleapis/cloud/dataproc/v1 expects import "google.golang.org/genproto/googleapis/clou
d/dataproc/v1"
```

I am wondering if I'm missing something. One could enumerate all the top directories, but that's not ideal.

Thanks

**Comment by mbana** [comment]
try something like this:

```yaml
- name: 'gcr.io/cloud-builders/go'
  args: ['get', '-t', '-u', './...']
  env: ['PROJECT_ROOT=github.com/banaio/openbanking_forgerock']
```

Note: the command fetches the test dependencies as well.
