### ISSUE TITLE
[docker] Possible to run concurrent docker images?

### ISSUE THREAD

**Issue by anr** [GoogleCloudPlatform/cloud-builders#325]
By reading this paragraph (found [here](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker#run-a-docker-image)):

"The step will complete when the container exits. If the image runs too long, the build may time out."

I have the impression that atm it is not possible to run multiple docker images at the same time. Is that the case? That would be a useful feature - eg for integration tests.

**Comment by bendory** [comment]
See [`waitFor`](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds#Build.BuildStep).

**Comment by anr** [comment]
Thanks.

Is there a way to make the build finish without using a `timeout` on a step? For instance, with this config the build will hang waiting for step 0 to finish:

```yaml
steps:
  - name: gcr.io/cloud-builders/docker
    args: ['run', '-p', '127.0.0.1:26257:26257', 'cockroachdb/cockroach:v2.0.4', 'start', '--insecure']
    waitFor: ['-']

  - name: gcr.io/cloud-builders/go
    args: ['get', './...']
    env: ['PROJECT_ROOT=${REPO_NAME}']
    id: get
    waitFor: ['-']

  # tests will use the db started above.
  - name: gcr.io/cloud-builders/go
    args: ['test', './foo/...']
    waitFor: ['get']
    env:  ['PROJECT_ROOT=${REPO_NAME}', 'DB_URL=${_DB_URL}']

substitutions:
  _DB_URL: bar
```

It feels a little bit like `waitFor` is being overloaded here, perhaps a new keyword meaning "don't add this step to the DAG and don't wait for it" could be useful?
