### ISSUE TITLE
Issues with gsutil rsync

### ISSUE THREAD

**Issue by jorilallo** [GoogleCloudPlatform/cloud-builders#336]
I'm running into issues running `gsutil` on Cloud Build. My workflow is pretty simple, compile JS assets and rsync them into a bucket (see config below). This works locally both in my own environment and on the Cloud Build simulator environment. On Cloud Build I get the following error which points that the built files aren't available in the location:

`CommandException: arg (build/production/web/client) does not name a directory, bucket, or bucket subdir.`

I did see something similar on the `gsutils`' issue tracker which leads me to believe that the gsutil might not have access to the local filesystem on Build, or something similar. Would there be an easy way to inspect the build environment etc in order to debug this?

```yaml
- name: 'gcr.io/cloud-builders/yarn'
  id: 'yarn'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/yarn'
  args: [
    'build-prod'
  ]
  id: 'client:build'
  waitFor: ['yarn']
- name: 'gcr.io/cloud-builders/gsutil'
  args: [
    'rsync',
    '-r',
    '-e',
    'build/production/web/client',
    'gs://issues-static/client'
  ]
  waitFor: ['client:build']
```
