### ISSUE TITLE
Add secret environment to docker builds

### ISSUE THREAD

**Issue by theblindprophet** [GoogleCloudPlatform/cloud-builders#345]
I am using Google Cloud Build integrated with Github. I have successfully created an encrypted `.env` file (`.env.enc`) with the KMS CLI, but the build step does not successfully copy the file into the workspace.

If I change `--plaintext-file=.env` to anything that does not have `.` in the front, `.env.enc` is successfully decrypted and dropped into the workspace. e.g. `--plaintext-file=environment-file.env`.

cloudbuild.yaml:
```
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=<key-ring-name>
  - --key=<key-name>
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/<name>:latest', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/<name>:latest']
images:
- 'gcr.io/$PROJECT_ID/<name>:latest'
```

**Comment by bendory** [comment]
Not sure I understand the bug report -- I think you are saying that the `--plaintext-file` flag works fine with hidden files (prefixed with `.`) but that the subsequent `docker build` command ignores the hidden file, is that right?

Do you have a `.dockerignore`? https://docs.docker.com/engine/reference/builder/#dockerignore-file

**Comment by theblindprophet** [comment]
`--plaintext-file` does **not** work with hidden files. They are not created at all.

**Comment by bendory** [comment]
Thanks for clarifying. Does `--plaintext-file` work with hidden files outside of GCB? (Meaning, does it work locally, but it doesn't work on your submitted build?)

I'm asking because I'm trying to route your bug report to the right place...
- if it works locally but doesn't work on submitted builds, that's a GCB problem that we need to figure out
- if it doesn't work locally, that's a KMS problem that needs to be reported to the KMS team

**Comment by bendory** [comment]
@theblindprophet I am unable to reproduce your problem. Here is my build configuration:

```
steps:
    - name: 'alpine'
      args: ['ls', '-la']
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['kms', 'decrypt', '--location=global', '--keyring=<ring>', '--key=<key>', '--ciphertext-file=.foo.enc', '--plaintext-file=.hidden.txt']
    - name: 'alpine'
      args: ['ls', '-la']
    - name: 'alpine'
      args: ['cat', '.hidden.txt']

```
Here's what's in my directory:
```
$ ls -a
./  ../  .foo.enc  test.yaml
$ 
```
Here's my build:
```
$ gcloud builds submit --config=test.yaml
Creating temporary tarball archive of 2 file(s) totalling 460 bytes before compression.
Uploading tarball of [.] to...
---------------------------------------------------------------------------------- REMOTE BUILD OUTPUT -----------------------------------------------------------------------------------
starting build...

FETCHSOURCE
Fetching storage object: gs://.../source/...
Copying gs://...
/ [1 files][  488.0 B/  488.0 B]                                                
Operation completed over 1 objects/488.0 B.                                      
BUILD
Starting Step #0
Step #0: Pulling image: alpine
Step #0: Using default tag: latest
Step #0: latest: Pulling from library/alpine
Step #0: Digest: sha256:0873c923e00e0fd2ba78041bfb64a105e1ecb7678916d1f7776311e45bf5634b
Step #0: Status: Downloaded newer image for alpine:latest
Step #0: total 16
Step #0: drwxr-xr-x    2 root     root          4096 Aug 29 14:05 .
Step #0: drwxr-xr-x    1 root     root          4096 Aug 29 14:05 ..
Step #0: -rw-r--r--    1 1003     89939          102 Aug 29 13:59 .foo.enc
Step #0: -rw-r--r--    1 1003     89939          358 Aug 29 14:05 test.yaml
Finished Step #0
Starting Step #1
Step #1: Already have image (with digest): gcr.io/cloud-builders/gcloud
Finished Step #1
Starting Step #2
Step #2: Already have image (with digest): alpine
Step #2: total 20
Step #2: drwxr-xr-x    2 root     root          4096 Aug 29 14:05 .
Step #2: drwxr-xr-x    1 root     root          4096 Aug 29 14:05 ..
Step #2: -rw-r--r--    1 1003     89939          102 Aug 29 13:59 .foo.enc
Step #2: -rw-r--r--    1 root     root            21 Aug 29 14:05 .hidden.txt
Step #2: -rw-r--r--    1 1003     89939          358 Aug 29 14:05 test.yaml
Finished Step #2
Starting Step #3
Step #3: Already have image (with digest): alpine
Step #3: Hello, hidden world!
Finished Step #3
...
```

Can you please provide a simple, reproducible test case that demonstrates the bug you are reporting?
