### ISSUE TITLE
Build completes but job errors as timed out

### ISSUE THREAD

**Issue by matthewbluezyoncom** [GoogleCloudPlatform/cloud-builders#359]
Running a multi-step build which uses yarn, npm, dotnet and docker builders.

I have had several builds which when looking at the log have completed, but the job status indicates a time out error.

Cloudbuild.yml as follows:

```
steps:
  - name: gcr.io/cloud-builders/yarn
    args: [install]
    dir: './src/App.Web/wwwroot/client'
  - name: gcr.io/cloud-builders/npm
    args: ['run','prod']
    dir: './src/App.Web/wwwroot/client'
  - name: gcr.io/cloud-builders/dotnet
    args: ['publish','-c','Release','-o','../../app']
    dir: './src/App.Web'
  - name: gcr.io/cloud-builders/docker
    args: ['build','-t','eu.gcr.io/$PROJECT_ID/App/$BRANCH_NAME:$REVISION_ID','-f','Dockerfile.build','.']
images: [eu.gcr.io/$PROJECT_ID/App/$BRANCH_NAME:$REVISION_ID]
timeout: 1h
options:
  machineType: 'N1_HIGHCPU_8'
```
