### ISSUE TITLE
.NET Core 2.2 please add support

### ISSUE THREAD

**Issue by klausmyrseth** [GoogleCloudPlatform/cloud-builders#374]
I noticed the docker image for .NET Core 2.2 is out, pls add it to the builder :)

**Comment by ImJasonH** [comment]
I think we'd prefer users to start using the [official `microsoft/dotnet:sdk` images provided by Microsoft, available on Dockerhub](https://hub.docker.com/r/microsoft/dotnet/).

In this case, the latest `microsoft/dotnet:sdk` provides version 2.1 of the SDK, so you'll need to explicitly specify `microsoft/dotnet:sdk-2.2` to get version 2.2.

You can use it like so:

```
steps:
- name: microsoft/dotnet:sdk-2.2
  entrypoint: dotnet
  args: ['--version']
```
