### ISSUE TITLE
Document how to connect to a database

### ISSUE THREAD

**Issue by kevinburke** [GoogleCloudPlatform/cloud-builders#376]
I am supposed to use the Go cloud builder to e.g. run Go programs or run tests, however, I have tests that are supposed to connect to a Postgres database and it's not clear to me how I am supposed to create or run a database with Google Cloud Build.

I have tried to read through/search the documentation on the website, as well as the "go" builder here, and the open/closed issues here.

**Comment by Philmod** [comment]
Hey @kevinburke , 

Are you planning to use an existing database on Google Cloud? In which case, your build should have easily access to it.

If you want to run a fresh/empty database for each build, you could use `docker-compose` to set it up. Here is an example: https://github.com/Philmod/gcb-docker-compose

**Comment by kevinburke** [comment]
I suppose I could use an existing database, but there would be concurrency problems, if there were two concurrent builders accessing the same tables.

This is a pretty common use case in a CI environment and I can find examples and easy configuration for any of your competitors:

https://docs.travis-ci.com/user/database-setup/#postgresql
https://circleci.com/docs/2.0/postgres-config/#example-go-app-with-postgresql
https://devcenter.heroku.com/articles/heroku-ci-in-dyno-databases
https://semaphoreci.com/docs/databases/postgresql.html

(finding those 4 links took me 1 minute tops)

**Comment by NinoFloris** [comment]
Good to see there's an open issue for this, very important to have some docs around this use case!

**Comment by markmssd** [comment]
@yetanotherchris I'm having the same issue to connect to Neo4J and run tests. Did you figure something out?

**Comment by vigandhi** [comment]
Using @yetanotherchris 's setup worked up to the same point - we're using Jest (24) and postgres. Everything seems fine until we try to run the tests, at which point, when we try to connect to the DB, everything just halts. The step (in my case it's step 7) completes successfully, but it seems like the process dies at the point where we try to connect to the DB - no error logs, no console logs (if we add them in) etc.

We're running the following npm script `"test:once": "node ./node_modules/jest/bin/jest.js -i --bail"`

With the below cloud build config
```
- name: gcr.io/cloud-builders/npm
  args: ['run', 'test:once']
```

**Comment by apstndb** [comment]
Cloud Build uses `cloudbuild` Docker network so we can minimize use of raw `docker run` and Docker Compose.

```
steps:
- name: gcr.io/cloud-builders/docker
  args: ['run', '-d', '--name=postgres', '--network=cloudbuild', 'postgres']
- name: jwilder/dockerize:0.6.1
  args: ['dockerize', '-timeout=60s', '-wait=tcp://postgres:5432']
- name: postgres
  args: ['psql', '--host=postgres', '--user=postgres', '--command', 'SELECT * FROM INFORMATION_SCHEMA.Tables']
# cloud-build-local don't clean `docker run -d`-ed container
- name: gcr.io/cloud-builders/docker
  args: ['rm', '--force', 'postgres']
```

**Comment by Datamance** [comment]
Is the above solution the recommended way to go?

**Comment by yetanotherchris** [comment]
With the help of @apstndb 's reply, this Cloud Build `cloudbuild.yaml` now works with .NET Core 3.1:

https://github.com/roadkillwiki/roadkill_new/blob/1984178d422fabf7a53e15c046d5dba7bf0de99c/cloudbuild.yaml

**Comment by sanastos** [comment]
I believe this is documented already:
https://cloud.google.com/cloud-build/docs/configuring-builds/build-test-deploy-artifacts#running_unit_tests_and_integration_tests

**Comment by apstndb** [comment]
The description in the document seems not to be sufficient.
There are no description about below.
- How to use `cloudbuild` network(`docker-compose.yml` is not contained in the document)
- What is [gcb-docker-compose](https://github.com/Philmod/gcb-docker-compose) (There are no links)
- How to communicate between containers by `docker run`(without Docker Compose) with `cloudbuild` network(discussed in this issue)

I don't think that every Cloud Build users who want to communicate between containers use Docker Compose in Cloud Build. Some users may even have never used Docker Compose.
`docker run` level example will be also useful to understand why they can communicate(and can't).

**Comment by sanastos** [comment]
The fact that the `cloudbuild` network exists and how it can be used with `docker run` is described in the build steps doc:
https://cloud.google.com/cloud-build/docs/build-config#network

I agree that the documentation does kind of imply that you must use docker compose, when `docker run` works just as well for simple dependencies (coincidentally I just addressed [this issue](https://github.com/GoogleCloudPlatform/cloud-build-local/issues/109)).

I will file a documentation bug to improve this section.

**Comment by marco-lavagnino** [comment]
> Hey @kevinburke ,
> 
> Are you planning to use an existing database on Google Cloud? In which case, your build should have easily access to it.
> 
> If you want to run a fresh/empty database for each build, you could use `docker-compose` to set it up. Here is an example: https://github.com/Philmod/gcb-docker-compose

Could you elaborate on "your build should have easily access to it"?

I don't see how to access my DB from a unix socket without running sql-proxy myself, while other services (like cloud run) can setup sql proxy from the UI. Is there something I'm missing?

**Comment by Datamance** [comment]
@yetanotherchris strangely, your solution doesn't work for me - dockerize itself seems to encounter problems:

`Step #1 - "wait-for-postgres": 2020/03/03 16:04:38 Problem with dial: dial tcp: lookup lookit-postgres on 127.0.0.11:53: no such host. Sleeping 1s`

Is it maybe better to run `dockerize` on the cloudbuild network as well?

**Comment by Datamance** [comment]
> I believe this is documented already:
> https://cloud.google.com/cloud-build/docs/configuring-builds/build-test-deploy-artifacts#running_unit_tests_and_integration_tests

That link is broken now - the fragment doesn't correspond to any sections.

**Comment by Datamance** [comment]
@apstndb Your solution doesn't work -

the following configuration:
```
steps:

- id: boot-postgres
  name: gcr.io/cloud-builders/docker
  args: ['run', '-d', '--publish=5432:5432', '--network=cloudbuild', '--name=postgres', 'postgres']


- id: wait-for-postgres
  name: jwilder/dockerize:0.6.1
  args: ['dockerize', '-timeout=60s', '-wait=tcp://postgres:5432']
```

dies because it waits until `dockerize` times out looking for the wrong host:
`Step #1 - "wait-for-postgres": 2020/03/03 16:52:33 Problem with dial: dial tcp: lookup postgres on 127.0.0.11:53: no such host. Sleeping 1s`

Has anyone else encountered this?

**Comment by apstndb** [comment]
@Datamance 
It should be because `postgres:latest` forbid default no password behavior without `POSTGRES_HOST_AUTH_METHOD=trust`.
https://hub.docker.com/_/postgres

It seems to work.
```yaml
steps:
- name: gcr.io/cloud-builders/docker
  args: ['run', '-d', '--network=cloudbuild', '--env=POSTGRES_HOST_AUTH_METHOD=trust', '--name=postgres', 'postgres:9.6']
- name: jwilder/dockerize:0.6.1
  args: ['dockerize', '-timeout=60s', '-wait=tcp://postgres:5432']
- name: postgres:9.6
  args: ['psql', '--host=postgres', '--user=postgres', '--command', 'SELECT * FROM INFORMATION_SCHEMA.Tables']
- name: gcr.io/cloud-builders/docker
  args: ['rm', '--force', 'postgres']
```
