### ISSUE TITLE
Differentiating between test, staging and prod.

### ISSUE THREAD

**Issue by larssb** [GoogleCloudPlatform/cloud-builders#395]
Hi there,

I have been through the documentation up on [Cloud build documentation](https://cloud.google.com/cloud-build/docs/) and I'm still having a hard time identifying a way to distinguish between building for test, staging and production environment.

1. You have a cloudbuild.yaml file in the root of a repository
2. You have installed the Google Cloud Build, GitHub app.
3. Builds are triggered on many different events. Not only when creating a pull request. So one could have a Cloud Build triggered for a feature branch. However, in that case you might not want all steps in the cloudbuild.yaml file executed.

In the above scenario. How is it possible to "tell" Google Cloud Build to pass on certain steps in the cloudbuild.yaml file?

Furthermore, is it in some way possible to output a variable or the like that can be used by a later step in the cloudbuild.yaml file.

Thank you.

**Comment by codrienne** [comment]
Hi,

We don't have first-class support for conditional steps, but you could use bash scripting to execute a step based on $BRANCH_NAME. 

```
# example.yaml, probably has typos
steps:
- name: 'some-builder'
   entrypoint: 'bash'
   args: ['-c', 'if [ "$BRANCH_NAME" == "master" ]; then .... ']
```

Does this help?
