### ISSUE TITLE
Using gcloud in nodejs test

### ISSUE THREAD

**Issue by JodusNodus** [GoogleCloudPlatform/cloud-builders#396]
As a step in the build config i test it. The nodeJs GAE app uses cloud storage. Gcloud authentication fails when executing it in this step. Is there a way to use the gcloud library without encrypting a service account keyFile?

**Comment by ImJasonH** [comment]
How are you running your step? We expose a metadata server which `gcloud` and other tools using Application Default Credentials should use to find your builder service account credentials.

https://cloud.google.com/docs/authentication/production#auth-cloud-compute-engine-nodejs

**Comment by JodusNodus** [comment]
This is my current config file for my GAE app.
```yaml
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']
    env:
    - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
```

**Comment by giovannibonetti** [comment]
I'm also facing a very similar issue, although in my case I'm trying to access Datastore.
My `cloudbuild.yaml` is identical to @JodusNodus one.

I have already added an IAM role to Cloud Builder to let it read/write Datastore Entities.

When I run the second step (`npm test`) I get an error like this:
```js
$ npm run test
(node:29) UnhandledPromiseRejectionWarning: Error: Unexpected error determining execution environment: Unsuccessful response status code. Request failed with status code 404
    at GoogleAuth.<anonymous> (/workspace/node_modules/google-auth-library/build/src/auth/googleauth.js:163:23)
    at Generator.throw (<anonymous>)
    at rejected (/workspace/node_modules/google-auth-library/build/src/auth/googleauth.js:20:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

It seems like the error is throw by this section that checks whether it is running on GCE:
```js
// node_modules/google-auth-library/build/src/auth/googleauth.js:157-164
// Determine if we're running on GCE.
let isGCE;
try {
    isGCE = yield this._checkIsGCE();
}
catch (e) {
    throw new Error('Unexpected error determining execution environment: ' + e.message);
}
```

Is there anything I should add in `cloudbuild.yaml` to let the `npm test` step get the credentials?
Maybe an environment variable?

**Comment by ImJasonH** [comment]
It looks like the NodeJS GCP auth library makes a request to `http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/<service-account-email>/token` to get the account's token ([source](https://github.com/googleapis/google-auth-library-nodejs/blob/8e18fddf42aaba39934a9dba3b3c7aff7840ba35/src/auth/computeclient.ts#L68)). If that's the case, that should respond with the service account's auth token. I'm not sure why it doesn't. I'll try to reproduce and see if that helps.

**Comment by ImJasonH** [comment]
@giovannibonetti (or anybody experiencing this) if you have a build ID I can investigate further.

FWIW, this build which does the ~same thing that the NodeJS library does works just fine (after replacing `<PROJECT_NUMBER>`). If you run it, be aware, it prints a temporary auth token to your logs, which you might not want to share.

```
steps:
- name: gcr.io/cloud-builders/curl
  args: ['-H', 'Metadata-Flavor: Google', 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token']
- name: gcr.io/cloud-builders/curl
  args: ['-H', 'Metadata-Flavor: Google', 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/<PROJECT_NUMBER>@cloudbuild.gserviceaccount.com/token']
```
