### ISSUE TITLE
cannot use cloudbuild.yaml to deploy to python flexible environment

### ISSUE THREAD

**Issue by mnbf9rca** [GoogleCloudPlatform/cloud-builders#397]
Although i can successfully use `gcloud app deploy` from my local machine, I get this error when i try to use cloud builder to deploy using python runtime to the flex environment e.g. with build 1db0be0d-9143-4ad4-9f1d-1d952d42c38e

`ERROR: (gcloud.app.deploy) There is a cloudbuild.yaml in the current directory, and the runtime field in /workspace/app.yaml is currently set to [runtime: python]. To use your cloudbuild.yaml to build a custom runtime, set the runtime field to [runtime: custom]. To continue using the [python] runtime, please remove the cloudbuild.yaml from this directory.`

app.yaml looks like this:
```
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT application:app

runtime_config:
    python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
    
<truncated>
```
cloudbuild.yaml looks like this:
```
steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
```
