### ISSUE TITLE
Use with private Bitbucket repo

### ISSUE THREAD

**Issue by pitw** [GoogleCloudPlatform/cloud-builders#400]
Did somebody made it work with a private bitbucket repo which includes dependencies to other private bitbucket repos?

Error I got every time:
```
Running: go get -t -u bitbucket.org/pitw/demoproject
package bitbucket.org/pitw/demoproject: https://api.bitbucket.org/2.0/repositories/pitw/demoproject?fields=scm: 403 Forbidden
```

Problem with bitbucket / go get is well known so I tried adding a step before go build like this:

```
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git config --global url."git@bitbucket.org:".insteadOf "https://bitbucket.org/"
  volumes:
  - name: 'ssh'
    path: /root/.ssh
```

But no effect. Did somebody manage to do this?
