### ISSUE TITLE
Using env files to set environments variables in a build step.

### ISSUE THREAD

**Issue by TheGrandmother** [GoogleCloudPlatform/cloud-builders#436]
I have a feature request that might very well be very stupid.

It would be very nice to be able to source env files in a build step that has been generated in a previous step.

I'm trying to create a build system with cloud build that builds and deploys to different clusters depending on the branch.
But this requires the setting of several cluster specific configurations (the names of databases, service account names, etc) that differs between the configurations.
It would be very very practical for me to be able to do something like:
```yaml
  #Load config
  - name: 'gcr.io/cloud-builders/ubuntu'
    entrypoint: 'bash'
    args:
      - './get-cluster-config.sh'
    volumes:
    - name: 'config'
      path: '/config'

  #Some other step
  - name: 'gcr.io/cloud-builders/gcloud'
    ...
    env_file:
      path:'/config/config_file'
    volumes:
    - name: 'config'
      path: '/config'
```

Since AFAIK there is no other way to do this apart from running bash in the build step and source the env files there. This of course work but it adds extra complexity to the build step.
