### ISSUE TITLE
docker 1.13

### ISSUE THREAD

**Issue by OmegaDroid** [GoogleCloudPlatform/cloud-builders#46]
Hi, are there currently any plans for using docker 1.13? `--cache-from` would make a big improvement to my build speeds.

**Comment by Philmod** [comment]
Hi Daniel,

We are looking into this upgrade, but have no specific date yet.

**Comment by bendory** [comment]
We have now upgraded to Docker 17.05, so --cache-from is available. Let us know how it goes!

**Comment by jakobholmelund** [comment]
i can't seem to get --cache-from to work

**Comment by skelterjohn** [comment]
Did you 'docker pull' the image into the job first? --cache-from won't work unless the image is already available on the host. Seems like an odd choice on their part, but there you go.

**Comment by ties** [comment]
This works for me, but a minimal `cloudbuild.yaml` example that included both the pull and build with `--cache-from` would have helped me.

**Comment by skelterjohn** [comment]
I'll see about getting an example in there.

In the meantime, this cloudbuild.yaml will do a `docker build` using the previous image built by the same build configuration as its cache.

```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/my-image']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/$PROJECT_ID/my-image', '-t', 'gcr.io/$PROJECT_ID/my-image', '.']
images: ['gcr.io/$PROJECT_ID/my-image']
```
