### ISSUE TITLE
GCB with golang image does not seem to cache go mod artifacts.

### ISSUE THREAD

**Issue by jeremyje** [GoogleCloudPlatform/cloud-builders#468]
I followed the steps outlined in the [golang build page](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/go) to produce outputs.

It seems if you use the golang image the go mod artifacts are not cached between build stages. So every build stage seems to redownload all the dependencies. The List files step shows the vendor/ directory populated so it's not clear what's going on here.

I've tried using go mod vendor as well to see if keeping the files in the source directory helps. It doesn't seem to work. I've also pre-vendored the directory outside of the build. And then start cloud-build-local from step "List Files" and I still see it's downloading dependencies though I can see the vendor/ directory is populated.

Here's my cloudbuild.yaml:
```yaml
steps:
- id: 'Setup: go mod'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'mod', 'init', 'github.com/GoogleCloudPlatform/open-match']
- id: 'Setup: Detect Dependencies'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'mod', 'tidy']
- id: 'Setup: Fix k8s.io/api Dependency'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'mod', 'edit', '-require', 'k8s.io/api@v0.0.0-20190111032252-67edc246be36']
- id: 'Setup: Vendor Dependencies'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'mod', 'vendor']
- id: 'List Files'
  name: golang
  args: ['find', '.', '-type', 'f']
- id: 'Lint: Formatting'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'fmt', './...']
- id: 'Lint: Vetting'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'vet', './...']
- id: 'Build: Application'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'build', './...']
- id: 'Test: 10x with Race Detection and Coverage'
  name: golang
  env: ['GO111MODULE=on']
  args: ['go', 'test', './...', '-race', '-test.count', '10', '-cover']
artifacts:
    objects:
        location: gs://jeremyje-om-build/builds/
        paths:
            - cmd/backendapi/backendapi
            - cmd/frontendapi/frontendapi
            - cmd/mmforc/mmforc
            - cmd/mmlogicapi/mmlogicapi
            - examples/backendclient/backendclient
```

**Comment by jeremyje** [comment]
I figured this out. You need to add a volume for the `/go` directory. This is because there are artifacts in the `/go/pkg` directory that need to be persisted.

It would be really helpful if the instructions in the README.md included this.

```yaml
- id: 'Setup: Pull Dependencies'
  name: golang
  env: ['GO111MODULE=on', 'CGO_ENABLED=0']
  args: ['go', 'mod', 'tidy']
  volumes:
  - name: 'go-vol'
    path: '/go'
  waitFor: ['Setup: go mod']
```
