### ISSUE TITLE
Env variable parameter substitution 

### ISSUE THREAD

**Issue by andrewmclagan** [GoogleCloudPlatform/cloud-builders#471]
Currently (I think) its not possible to assign default values to environment variables in build steps. This is a common feature of CI/CD tooling and bash. It allows engineers to easily provide default fallbacks for variables in cases where they are not present - for more flexible / generic pipeline definitions.

#### Example A:

```bash
TAG_NAME=""
SHORT_SHA=""
```
```yaml
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/web-app:${TAG_NAME=${SHORT_SHA=latest}}', '.']
    dir: 'api-core'
```
Equates to:
```bash
docker build -t asia.gcr.io/my-project/web-app:latest .
```

#### Example B:

```bash
TAG_NAME=""
SHORT_SHA="921103db8259eb9de7"
```
```yaml
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/web-app:${TAG_NAME=${SHORT_SHA=latest}}', '.']
    dir: 'api-core'
```
Equates to:
```bash
docker build -t asia.gcr.io/my-project/web-app:921103db8259eb9de7 .
```
#### Example C:

```bash
TAG_NAME="v1.0.0"
SHORT_SHA="921103db8259eb9de7"
```
```yaml
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/web-app:${TAG_NAME=${SHORT_SHA=latest}}', '.']
    dir: 'api-core'
```
Equates to:
```bash
docker build -t asia.gcr.io/my-project/web-app:v1.0.0 .
```

## Additional Info

Tracked: https://issuetracker.google.com/issues/128869870
