### ISSUE TITLE
gcloud unable to get access token

### ISSUE THREAD

**Issue by Rohithzr** [GoogleCloudPlatform/cloud-builders#483]
Today, out of nowhere, my cloud builds started to fail due to an issue I believe is with cloud builder.

cloud-builder: gcr.io/cloud-builders/gcloud
error: error executing access token command 
possible cause: snap 77 is not available (78+ is available)

my cloudbuild.yaml
```yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '--build-arg',
    'CREDS_GCS=${_CREDS_GCS}',
    '-t', 
    'gcr.io/$PROJECT_ID/$BRANCH_NAME-$REPO_NAME:$COMMIT_SHA', 
    '.']
  env:
  - 'CREDS_GCS=$_CREDS_GCS'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$BRANCH_NAME-$REPO_NAME:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'cloudbuild@cc-bastion', '--', 'kubectl set image deployment/$BRANCH_NAME-backend backend=gcr.io/$PROJECT_ID/$BRANCH_NAME-$REPO_NAME:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
```

logs
```
Starting Step #2
Step #2: Already have image (with digest): gcr.io/cloud-builders/gcloud
Step #2: WARNING: The public SSH key file for gcloud does not exist.
Step #2: WARNING: The private SSH key file for gcloud does not exist.
Step #2: WARNING: You do not have an SSH key for gcloud.
Step #2: WARNING: SSH keygen will be executed to generate a key.
Step #2: This tool needs to create the directory [/builder/home/.ssh] before 
Step #2: being able to generate SSH keys.
Step #2: 
Step #2: Do you want to continue (Y/n)? 
Step #2: Generating public/private rsa key pair.
Step #2: Your identification has been saved in /builder/home/.ssh/google_compute_engine.
Step #2: Your public key has been saved in /builder/home/.ssh/google_compute_engine.pub.
Step #2: The key fingerprint is:
Step #2: SHA256:XXX
Step #2: The key's randomart image is:
...
Step #2: +----[SHA256]-----+
Step #2: Updating project ssh metadata...
Step #2: .........................................................................................................failed.
Step #2: Updating instance ssh metadata...
Step #2: .....................................Updated [https://www.googleapis.com/compute/v1/projects/project-name/zones/us-central1-c/instances/cc-bastion].
Step #2: .done.
Step #2: Waiting for SSH key to propagate.
Step #2: Warning: Permanently added 'compute.679072732982018777' (ECDSA) to the list of known hosts.
Step #2: Pseudo-terminal will not be allocated because stdin is not a terminal.
Step #2: Unable to connect to the server: error executing access token command "/snap/google-cloud-sdk/77/bin/gcloud config config-helper --format=json": err=fork/exec /snap/google-cloud-sdk/77/bin/gcloud: no such file or directory output= stderr=
Finished Step #2
ERROR
ERROR: build step 2 "gcr.io/cloud-builders/gcloud" failed: exit status 1
```
