### ISSUE TITLE
docker.io/docker/dockerfile:1.0.0-experimental not found

### ISSUE THREAD

**Issue by ralucas** [GoogleCloudPlatform/cloud-builders#506]
## Affected builder image
`gcr.io/cloud-builders/docker`

## Expected Behavior
The ability to use `RUN --mount=type=secret,...`

## Actual Behavior
Cannot use because the syntax is not available

## Steps to Reproduce the Problem

1. At the top of the Dockerfile: `# syntax=docker/dockerfile:1.0.0-experimental`
2. Use the `RUN --mount` command in the Dockerfile

**Comment by TAvardit** [comment]
And it is working successfully with `cloud-build-local`.

**Comment by hawksight** [comment]
So I guess locally it hooks into whatever docker version you have installed (I'd assume)

I'm also looking to use `--mount` to provide access to private git repos for pulling an app's dependencies.

Looking [at docs](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker#older-versions) and at [container registry](https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL/docker?gcrImageListsize=30&gcrImageListquery=%255B%255D) for any more recent versions but only seeing 18.09.6.

Tried to check the docker version in cloud-build before running a build:
```
Already have image (with digest): gcr.io/cloud-builders/docker
Client: Docker Engine - Community
Version: 19.03.3
API version: 1.39 (downgraded from 1.40)
Go version: go1.12.10
Git commit: a872fc2
Built: Tue Oct 8 00:59:54 2019
OS/Arch: linux/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.3
API version: 1.39 (minimum version 1.12)
Go version: go1.10.8
Git commit: 774a1f4
Built: Thu Feb 28 05:59:55 2019
OS/Arch: linux/amd64
Experimental: false
```

Can you provide your own builder images for cloud-build? 
Or is one in the works with Buildkit enabled? (noticed the experimental flag was false above)

**Comment by Yanson** [comment]
I am facing the same issue. I would have expected it to work as it is a 18.09 feature with API 1.39 which is what @hawksight has shown is available.

https://docs.docker.com/develop/develop-images/build_enhancements/
https://docs.docker.com/engine/reference/commandline/build/

Works fine in cloud-build-local:
```yaml
- id: 'build'
  waitFor: ['secrets']
  name: 'gcr.io/cloud-builders/docker:18.09.6'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/foo:bar', '--secret=id=x,src=/.secrets/x', '.']
  env:
  - DOCKER_BUILDKIT=1
```

**Comment by Yanson** [comment]
As per [this](https://github.com/moby/moby/issues/39120#issuecomment-562587888) comment, the following workaround resolves this for now:

```yaml
- id: 'pull-experimental'
  waitFor: ['-']
  name: 'gcr.io/cloud-builders/docker:18.09.6'
  args: ['pull', 'docker.io/docker/dockerfile:1.0-experimental']
  env:
  - DOCKER_BUILDKIT=1

- id: 'build'
  waitFor: ['secrets', 'pull-experimental']
  name: 'gcr.io/cloud-builders/docker:18.09.6'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/foo:bar', '--secret=id=x,src=/.secrets/x', '.']
  env:
  - DOCKER_BUILDKIT=1
```
