### ISSUE TITLE
Git LFS in Git builder fails

### ISSUE THREAD

**Issue by Neo-Zhixing** [GoogleCloudPlatform/cloud-builders#509]
## Affected builder image

gcr.io/cloud-builders/git

## Expected Behavior

```yaml
- name: 'gcr.io/cloud-builders/git'
  args: ['lfs', 'pull']
```
This step pulls all git lfs files

## Actual Behavior

```
Already have image (with digest): gcr.io/cloud-builders/git
git: 'lfs' is not a git command. See 'git --help'.
```
It seems like git-lfs does not exist in the build environment.
How can I install the git-lfs plugin and fetch the git lfs files from my repository?

**Comment by Neo-Zhixing** [comment]
I ended up doing this:

In a separate directory, create Dockerfile:
```
FROM alpine
RUN apk --no-cache add git git-lfs
ENTRYPOINT ["/usr/bin/git"]
```
And create cloudbuild.yaml;
```yaml
steps:
- name: "gcr.io/cloud-builders/docker"
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/git-lfs', '.']
images:
- "gcr.io/$PROJECT_ID/git-lfs"
```
Run `gcloud builds submit`, and you'll get a 'git-lfs' image in your container registry.

Finally, use the new git-lfs image to pull the lfs files.
In the target project cloudbuild.yml:
```yaml
- name: 'gcr.io/$PROJECT_ID/git-lfs'
  args: ['init']
- name: 'gcr.io/$PROJECT_ID/git-lfs'
  args: ['remote', 'add', 'origin', '[REPO_ADDRESS]']
- name: 'gcr.io/$PROJECT_ID/git-lfs'
  args: ['fetch']
- name: 'gcr.io/$PROJECT_ID/git-lfs'
  args: ['reset', '--soft', 'origin/$BRANCH_NAME']
- name: 'gcr.io/$PROJECT_ID/git-lfs'
  args: ['lfs', 'fetch']
```

This is obviously very complicated and hacky, so it would be much better for the Cloud Build team to natively support git-lfs for GitHub triggers.
