### ISSUE TITLE
gcr.io/cloud-builders/gsutil broken in newer versions

### ISSUE THREAD

**Issue by tlbdk** [GoogleCloudPlatform/cloud-builders#511]
When trying to run the following command get the following error:

``` yaml
 # push shared state to cloud bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-q', '-m', 'rsync', '-d', '-r', 'build/sstate-cache', 'gs://bucket-name']
```

``` text
Step #12: too many values to unpack
Step #12: CommandException: 1 files/objects could not be copied/removed.
```
On an older container it works without issue:

``` yaml
 # push shared state to cloud bucket
  - name: 'gcr.io/cloud-builders/gsutil@sha256:dc0689563c2d96766095b6937e82a2d94f87c3173ad97251648a6b944e432473'
    args: ['-q', '-m', 'rsync', '-d', '-r', 'build/sstate-cache', 'gs://bucket-name']
```
