### ISSUE TITLE
Npm install from Google Source Repositories in Cloud Build

### ISSUE THREAD

**Issue by karatekaneen** [GoogleCloudPlatform/cloud-builders#538]
## Affected builder image
gcr.io/cloud-builders/npm

## Expected Behavior

Want to `npm install` private package from Google Source in my build process.

## Actual Behavior

Authorization failed

## Steps to Reproduce the Problem

In my development env I started with this in `package.json`:
```json
"dependencies": {
		"package": "git+https://source.developers.google.com/p/*project*/r/*package*",
		...
}
```

In my build file i try with this:
```yaml
steps:
# Get credentials:
- name: 'gcr.io/cloud-builders/git'
  id: Credentials
  args:
  - 'config'
  - '--global'
  - 'credential.helper'
  - 'gcloud.sh'
# This step installs the app
- name: 'gcr.io/cloud-builders/npm'
  id: Install
  args:
  - 'install'
  
# This step runs the tests
- name: 'gcr.io/cloud-builders/npm'
  id: Test
  args:
  - 'run'
  - 'test:unit'
...
```

This fails with:
```
Step #0 - "Install": npm ERR! Error while executing:
Step #0 - "Install": npm ERR! /usr/bin/git ls-remote -h -t https://source.developers.google.com/p/*project*/r/*package*
Step #0 - "Install": npm ERR! 
Step #0 - "Install": npm ERR! git: 'credential-gcloud.sh' is not a git command. See 'git --help'.
Step #0 - "Install": npm ERR! git: 'credential-gcloud.sh' is not a git command. See 'git --help'.
Step #0 - "Install": npm ERR! fatal: remote error: 
Step #0 - "Install": npm ERR! 
Step #0 - "Install": npm ERR! 
Step #0 - "Install": npm ERR! Invalid authentication credentials.
Step #0 - "Install": npm ERR! 
Step #0 - "Install": npm ERR! Please generate a new identifier:
Step #0 - "Install": npm ERR!   https://source.developers.google.com/new-password
Step #0 - "Install": npm ERR! 
Step #0 - "Install": npm ERR! 
Step #0 - "Install": npm ERR! 
Step #0 - "Install": npm ERR! exited with error code: 128
```

So after spending a day googling and looking for good solutions I've not found anything that seems like the "correct" way of doing this.

### The best solution so far is: 

Generating a ssh key to be able to clone the package. This works but since it seems like I need to have the email in the string as `"package": "git+ssh://service.account@company.se@source.developers.google.com:2022/p/project/r/package"` I need to change the email between commiting and building.

Anyone got a better suggestion of doing this?
