### ISSUE TITLE
Gsutil setmeta cache control header

### ISSUE THREAD

**Issue by AdriVanHoudt** [GoogleCloudPlatform/cloud-builders#557]
## Affected builder image

gcr.io/cloud-builders/gsutil

## Expected Behavior

It sets the cache control headers

## Actual Behavior

I get this error `CommandException: Invalid or disallowed header ( "Cache-Control).`

## Steps to Reproduce the Problem

Current config:
```yaml
  - id: never-cache
    name: gcr.io/cloud-builders/gsutil
    args:
      - '-m'
      - 'setmeta'
      - '-r'
      - |
        -h "Cache-Control:private max-age=0, no-transform, no-cache, must-revalidate"
      - 'gs://${_URL}/index.html'
```
I've tried a bunch of variations, from lower casing the cache-control, different versions of specifying args, single quotes, quoted single quotes, ...
But none seem to work
