### ISSUE TITLE
Bazel Builder: /builder/outputs/output: Permission denied

### ISSUE THREAD

**Issue by AtaS** [GoogleCloudPlatform/cloud-builders#567]
Hi,

By default `gcr.io/cloud-builders/bazel` is outputting the error:
```
Step #1: /usr/bin/bazel: line 43: /builder/outputs/output: Permission denied
```

Using this environment variable resolves the issue but it is not documented and I don't know if this env variable is officially supported.

```
env:
      - 'BUILDER_OUTPUT=/workspace/.bazel'
```

Also we need to create the .bazel folder so bazel can work in it.

## Affected builder image

(e.g., `gcr.io/cloud-builders/bazel`)

## Expected Behavior

```
  - name: 'gcr.io/cloud-builders/bazel'
    args: ['version']```

Outputs the version

## Actual Behavior

Outputs:
```
Step #1: /usr/bin/bazel: line 43: /builder/outputs/output: Permission denied
```

## Steps to Reproduce the Problem

1. Have a cloudbuild.yaml as:
```  
steps:
  - name: 'gcr.io/cloud-builders/bazel'
    args: ['version']
```

2.  Run
```
cloud-build-local --dryrun=false .
```
