### ISSUE TITLE
Issue with gcloud composer environments run --location parameter 

### ISSUE THREAD

**Issue by jaketf** [GoogleCloudPlatform/cloud-builders#590]
## Affected builder image
 `gcr.io/cloud-builders/gcloud`

## Expected Behavior
```yaml
- name: gcr.io/cloud-builders/gcloud
  dir: '${REPO_NAME}/'
  args: ['--version']
  id: 'gcloud-version'
```
should print something with latest gcloud version e.g.
```
Google Cloud SDK 272.0.0
...
```

## Actual Behavior
instead getting
```
Already have image (with digest): gcr.io/cloud-builders/gcloud
Google Cloud SDK 266.0.0
alpha 2019.05.17
app-engine-go 
app-engine-java 1.9.76
app-engine-php " "
app-engine-python 1.9.86
app-engine-python-extras 1.9.86
beta 2019.05.17
bigtable 
bq 2.0.48
cbt 
cloud-build-local 
cloud-datastore-emulator 2.1.0
core 2019.10.04
datalab 20190610
docker-credential-gcr 
emulator-reverse-proxy 
gsutil 4.44
kubectl 2019.09.22
pubsub-emulator 2019.09.27
```
## Steps to Reproduce the Problem

1.
Used this cloudbuild.yaml
```yaml
- name: gcr.io/cloud-builders/gcloud
  dir: '${REPO_NAME}/'
  args: ['--version']
  id: 'gcloud-version'
```

2. observed output in cloud build console.

## Additional Info
I discovered this by trying to use the gcloud builder to execute a go program (compiled in a previous step of my build) which uses `exec.Cmd` to call various gcloud commands. In this case running 
```
gcloud composer environments run datapipelines-orchestration --location=us-central1 list_dags
```
yielded a strange error for a valid location
```
2019/11/22 23:40:40 list_dags failed: exit status 1 with ERROR: (gcloud.composer.environments.run) INVALID_ARGUMENT: Unexpected location: us-central1,
```
