### ISSUE TITLE
Need help with cloud build to deploy cloud function

### ISSUE THREAD

**Issue by riteshnanda09** [GoogleCloudPlatform/cloud-builders#598]
## Affected builder image

`gcr.io/cloud-builders/go`

## Expected Behavior
I am trying to trigger deploy cloud function through cloud build which pull source from cloud source . Repo structure is plain with files

```
.gcloudignore
.gitignore
bucket.go
build.yaml
cmek.go
initilize.go
```

with build.yaml looking as 

```yaml
steps:
- name: 'gcr.io/cloud-builders/go'
  env: ['GO111MODULE=on', 'PROJECT_ROOT=cmekbucket']
  args: ['mod', 'init']
- name: 'gcr.io/cloud-builders/go'
  env: ['GO111MODULE=on', 'PROJECT_ROOT=cmekbucket']
  args: ['mod', 'tidy']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - cmekBucketdetection 
  - --source=/cmekbucket
  - --trigger-topic=cmekbucket
  - --runtime=go111
```

I am not sure about how what should be the source for step2 `gcloud deploy functions`

## Actual Behavior

I tried multiple iteration with the directory as well didn't find much documentation with respect to cloud build and cloud function . First two steps are successful , basically generating go.mod and go.sum , third step fails with
```
Starting Step #2
Step #2: Already have image (with digest): gcr.io/cloud-builders/gcloud
Step #2: ERROR: (gcloud.functions.deploy) argument `--source`: Provided directory does not exist
Finished Step #2
ERROR
ERROR: build step 2 "gcr.io/cloud-builders/gcloud" failed: exit status 1
```

Doing deployment gcloud command runs fine with steps
1. GO111MODULE=on go mod init
2. GO111MODULE=on go mod tidy
3. `gcloud functions deploy `example` --runtime go111 --trigger-topic something --entry-point PubSub`
