### ISSUE TITLE
Upgrade gcr.io/cloud-builders/gcloud to Python 3.7+

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/cloud-builders#601]
## Affected builder image

`gcr.io/cloud-builders/gcloud:latest`

## Expected Behavior

Running a recent version of Python 3.x (3.7, 3.8)

## Actual Behavior

Still running Python 3.5, which is now not only nearing the EOL (2020-09-13), but is also unsupported by many third-party packages.

As a workaround, we have to use other (custom) builders, which take substantially longer time to pull.

## Steps to Reproduce the Problem

```
steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: python3
  args: ['--version']
```
Output: `Python 3.5.2`

## Additional Info

Thanks!
