### ISSUE TITLE
How to use gke-deploy with kustomize in Cloud Build

### ISSUE THREAD

**Issue by WLun001** [GoogleCloudPlatform/cloud-builders#629]
## Affected builder image

(e.g., `gcr.io/cloud-builders/gke-deploy`)

## Expected Behavior
Able to use kustomize from gke-deploy image
## Actual Behavior
Error on Cloud Build
` \"kustomize\": executable file not found in $PATH": unknown`

## Steps to Reproduce the Problem

I thought kustomize is included in kubectl, and i see the docker file has kubectl installed
https://github.com/GoogleCloudPlatform/cloud-builders/blob/6beb33eca5566c6bf32d8e955a7c56ed6f6a0d0a/gke-deploy/Dockerfile#L7
here is my cloudbuild.yaml

attempt 1
```yaml
  - name: 'gcr.io/cloud-builders/gke-deploy:stable'
    id: 'gke-deploy'
    entrypoint: 'kustomize'
    args:
      - 'build'
      - '$_KUSTOMIZE_PATH'
      - '|'
      - 'gke-deploy'
      - 'run'
      - '-f'
      - '-'
      - '--image=asia.gcr.io/$PROJECT_ID/api:$SHORT_SHA'
      - '--label=commit-sha=$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
```

attempt 2
```diff
  - name: 'gcr.io/cloud-builders/gke-deploy:stable'
    id: 'gke-deploy'
+  entrypoint: 'bash'
    args:
+    - 'kustomize'
      - 'build'
      - '$_KUSTOMIZE_PATH'
      - '|'
      - 'gke-deploy'
      - 'run'
      - '-f'
      - '-'
      - '--image=asia.gcr.io/$PROJECT_ID/mp-api:$SHORT_SHA'
      - '--label=commit-sha=$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
```

attempt 3
```diff
  - name: 'gcr.io/cloud-builders/gke-deploy:stable'
    id: 'gke-deploy'
+  entrypoint: 'sh'
    args:
+    - 'kustomize'
      - 'build'
      - '$_KUSTOMIZE_PATH'
      - '|'
      - 'gke-deploy'
      - 'run'
      - '-f'
      - '-'
      - '--image=asia.gcr.io/$PROJECT_ID/mp-api:$SHORT_SHA'
      - '--label=commit-sha=$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
```

attempt 4

```yaml
  - name: 'gcr.io/cloud-builders/gke-deploy:stable'
    id: 'gke-deploy'
    entrypoint: 'kubectl'
    args:
      - 'kustomize'
      - '$_KUSTOMIZE_PATH'
      - '|'
      - 'gke-deploy'
      - 'run'
      - '-f'
      - '-'
      - '--image=asia.gcr.io/$PROJECT_ID/mp-api:$SHORT_SHA'
      - '--label=commit-sha=$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
```

Non of one of these working
Any recommended way to use gke-deploy with kustomize?

**Comment by WLun001** [comment]
The issue is due to `kubectl` version

```shell
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.9-2+4a03651a7e7e04", GitCommit:"4a03651a7e7e04a0021b2ef087963dfb7bd0a17e", GitTreeState:"clean", BuildDate:"2019-08-16T18:57:20Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by WLun001** [comment]
Another attempt, with `latest` image tag
Hitting this error on both config
`bash: ./gke-deploy: No such file or directory`

```yaml
  - name: 'gcr.io/cloud-builders/gke-deploy:latest'
    id: 'gke-deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl kustomize $_KUSTOMIZE_PATH | ./gke-deploy run -f - --image=asia.gcr.io/$PROJECT_ID/mp-api:$SHORT_SHA --label=commit-sha=$SHORT_SHA
```


```yaml
  - name: 'gcr.io/cloud-builders/gke-deploy:latest'
    id: 'gke-deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl kustomize $_KUSTOMIZE_PATH | gke-deploy run -f - --image=asia.gcr.io/$PROJECT_ID/mp-api:$SHORT_SHA --label=commit-sha=$SHORT_SHA
```

**Comment by joonlim** [comment]
Hi @WLun001, I'd recommend running them as two separate steps:

```
  - name: 'gcr.io/cloud-builders-community/kustomize'
    args:
      - 'build'
      - '$_KUSTOMIZE_PATH'
      - '-o'
      - '/workspace/resources.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '-f'
      - '/workspace/resources.yaml'
      - '--image=asia.gcr.io/$PROJECT_ID/mp-api:$SHORT_SHA'
      - '--label=commit-sha=$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
```

I hope that helps

**Comment by kdeggelman** [comment]
Given the addition of `kustomize` in https://github.com/GoogleCloudPlatform/cloud-builders/pull/748, I'm curious what the current recommendation is here.

One modification to @joonlim's suggestion above no longer relies on `gcr.io/cloud-builders-community/kustomize`

```yaml
  - name: 'gcr.io/cloud-builders/gke-deploy'
    entrypoint: 'kustomize'
    args:
      - 'build'
      - '$_KUSTOMIZE_PATH'
      - '-o'
      - '/workspace/resources.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
  
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '-f'
      - '/workspace/resources.yaml'
      - '--image=asia.gcr.io/$PROJECT_ID/mp-api:$SHORT_SHA'
      - '--label=commit-sha=$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
 ```

I'm kind of surprised that this takes two steps (although the first step runs so quickly that it's almost inconsequential). Just out of curiousity, is there a reason why `gke-deploy run` doesn't support a `-k` flag like `kubectl` does?
