### ISSUE TITLE
gke-deploy – Error: value must not be empty string

### ISSUE THREAD

**Issue by onsails** [GoogleCloudPlatform/cloud-builders#652]
With helpful information in #629 from @joonlim I am trying to instruct cloudbuild to buid kustomize and deploy it with the newly built artefact.

## Affected builder image

`gcr.io/cloud-builders/gke-deploy`

## Expected Behavior

Deploy happens

## Actual Behavior

Non-descriptive error on gke-deploy step:
```
Starting Step #2
Step #2: Already have image (with digest): gcr.io/cloud-builders/gke-deploy
Step #2: Error: value must not be empty string
Finished Step #2
```

## Steps to Reproduce the Problem

```yaml cloudbuild.yaml
steps:

- name: gcr.io/kaniko-project/executor:latest
  args:
  - --dockerfile=Dockerfile
  - --destination=gcr.io/$PROJECT_ID/frontend:$SHORT_SHA
  - --cache=true
  # apt-get checks
  - --cache-ttl=96h
  timeout: 1200s # == 20m

- name: gcr.io/$PROJECT_ID/kustomize
  args:
    - 'build'
    - './kube'
    - '-o'
    - '/workspace/resources.yaml'
  env:
    - CLOUDSDK_COMPUTE_ZONE=${_LOCATION}
    - CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}
    - GCLOUD_PROJECT=$PROJECT_ID

- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
    - run
    - --filename=/workspace/resources.yaml
    - --image=gcr.io/$PROJECT_ID/frontend:$SHORT_SHA
    - --label=commit-sha=$SHORT_SHA
    - --location=${_LOCATION}
    - --cluster=${_CLUSTER}
  
substitutions:
  _LOCATION: europe-north1-c
  _CLUSTER: my-cluster

timeout: 3600s # == 1h
```

```bash
gcloud builds submit . --config=cloudbuild.yaml --substitutions=...
```

**Comment by andresetevejob** [comment]
Hi, what is the content of your resource.yaml ??

**Comment by onsails** [comment]
resources.yaml:
```
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: myapp-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: myapp-frontend
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    app: frontend-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: myapp
    app.kubernetes.io/version: v1
  name: frontend
  namespace: myapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-svc
  template:
    metadata:
      labels:
        app: frontend-svc
    spec:
      containers:
      - image: gcr.io/myapp/mb-frontend
        imagePullPolicy: ""
        name: frontend-svc
        ports:
        - containerPort: 80
          name: web
        resources:
          requests:
            cpu: 100m
      serviceAccountName: web
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: myapp-dev-issuer-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
  name: frontend
  namespace: myapp-frontend
spec:
  rules:
  - host: app.myapp.dev
    http:
      paths:
      - backend:
          serviceName: frontend-svc
          servicePort: 80
  tls:
  - hosts:
    - app.myapp.dev
    secretName: frontend
```
