### ISSUE TITLE
Persistent volumes between stages are empty

### ISSUE THREAD

**Issue by ggunia** [GoogleCloudPlatform/cloud-builders#656]
## Affected builder image

`gcr.io/cloud-builders/docker`
`gcr.io/cloud-builders/gsutil`

## Expected Behavior
Transfer referenced folder location to bucket

## Actual Behavior
Build is succeeding but does not transfer anything

## Additional Info
This is the cloud build file
```
steps:
  - name: 'gcr.io/cloud-builders/docker'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume' 
    args: ['build', '-f', 'Dockerfile.production', '-t', [image-name-placeholder], '.']

  - name: 'gcr.io/cloud-builders/gsutil'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume'
    args: ['-m', 'rsync', '-r', '-d', '/persistent_volume/data/', 'gs://example-destination']
```

This is the docker file

```
WORKDIR /persistent_volume
RUN mkdir data
WORKDIR /persistent_volume/data
RUN touch index.html
```
