### ISSUE TITLE
Add data from Google Cloud Storage to image to be built

### ISSUE THREAD

**Issue by ToddMorrill** [GoogleCloudPlatform/cloud-builders#697]
I'm hoping this a fairly easy question to answer. I'm building a machine learning model server. I have model weights stored on Google Cloud Storage. I want to download those model weights into my server image and push the resulting image to Google Container Registry. How do I do that?

So far, I'm doing this in my `couldbuild.yaml` file.
```
steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: [ 'cp', 'gs://my-bucket/model/runs/20200610-183126/params.pt', '/persistent_volume/model/runs/20200610-183126' ]
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/my-project/sample-python-app:test', '.']
  volumes:
    - name: 'vol1'
      path: '/persistent_volume'
images:
- 'gcr.io/my-project/sample-python-app:test'
```

Clearly, this is only mounting a temporary volume at each step and none of that downloaded data is being persisted in my image `gcr.io/my-project/sample-python-app:test`.

I _don't_ want to include the model weights in my build context and add a `COPY` command in my Dockerfile because my build context is a git repo and I've always kept code and data separate.

I've recently come across [multistage builds](https://docs.docker.com/develop/develop-images/multistage-build/), which  seem to do exactly what I want. The only downside is that it looks like I'll need to manage authentication to Google Cloud Storage, whereas by using `gcr.io/cloud-builders/gsutil` with Cloud Build, authentication is taken care of for me.

Please let me know what the best way forward is here. Thank you for any help you can offer!
