### ISSUE TITLE
README Example Doesn't Work

### ISSUE THREAD

**Issue by dinagraves** [GoogleCloudPlatform/cloud-builders#698]
I tried pasting in the example under "[Sharing packages across steps](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/go#note-2-sharing-packages-across-steps)" and received this error:

```
Starting Step #1
Step #1: Already have image: golang
Step #1: go list -m: module github.com/golang/glog: not a known dependency
Finished Step #1
ERROR
ERROR: build step 1 "golang" failed: step exited with non-zero status: 1
```

My cloudbuild was very simply copy and pasted from the example:

```
- name: golang
  env:
  - GO111MODULE=on
  args: ['go','get','-u','github.com/golang/glog']
  volumes:
  - name: go-modules
    path: /go

- name: golang
  env:
  - GO111MODULE=on
  args: ['go','list','-f','{{ .Dir }}','-m','github.com/golang/glog']
  volumes:
  - name: go-modules
    path: /go
```
