### ISSUE TITLE
Rollout restart failing

### ISSUE THREAD

**Issue by akshatgit** [GoogleCloudPlatform/cloud-builders#709]
## Issue
Trying to `rollout restart` a deployment from builder.  Googled around the issue, saw [posts](https://stackoverflow.com/questions/58746806/cloud-build-rollout-restart-not-recognized-unknown-command) where its mentioned rollout restart is a new feature and is not available in older clients. 
However, in `kubectl rollout --help` it shows restart is available.
```
Available Commands:
  history     View rollout history
  pause       Mark the provided resource as paused
  restart     Restart a resource
  resume      Resume a paused resource
  status      Show the status of the rollout
  undo        Undo a previous rollout
```

## Affected builder image

gcr.io/cloud-builders/kubectl

## Expected Behavior
The deployment should be restarted in a rolling manner.

## Actual Behavior
`error: unknown command "restart deployment/<deployment_name>"`

## Steps to Reproduce the Problem

1.  `kubectl rollout restart deployment/<deployment_name>  -n <namespace>`

## Additional Info

I am running a bash script by changing the entrypoint. 
My cloudbuild is as follows:

```
- id: 'Deploy to GKE'
  name: "gcr.io/cloud-builders/kubectl:latest"
  entrypoint: 'bash'
  args: ['./deploy.sh']
  env:
  - 'ZONE=$_ZONE'
  - 'PROJECT=$_PROJECT'
  - 'CLUSTER=$_CONTAINER_CLUSTER'
  - 'BRANCH=$BRANCH_NAME'
```
