### ISSUE TITLE
Issues with ASP.NET Builder

### ISSUE THREAD

**Issue by TomasWeg** [GoogleCloudPlatform/cloud-builders#722]
I cannot use the .NET builder because it says:
` error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.`

This is my cloudbuild.yaml
```
# Example build script to create a Docker image from a .NET Core 2.0 Web Api app.
steps:

- name: 'microsoft/dotnet:sdk'
  entrypoint: dotnet
  args: [ 'publish', '-c', 'Release', '-o', 'release' ]

# Build the app image.
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/admin-panel:$BUILD_ID', '.' ]
  dir: './release'

# Publish the app.
images: [ 'gcr.io/$PROJECT_ID/admin-panel:$BUILD_ID' ]
```
