### ISSUE TITLE
[Question/Help] Git unable to switch branch 

### ISSUE THREAD

**Issue by gogovan-vincentngai** [GoogleCloudPlatform/cloud-builders#737]
I am using Jenkins and Plugin https://plugins.jenkins.io/google-cloudbuild/ 
But i think not really related ....
Because i see all cmd send from jenkins at GCP side and error happen in Cloud Build level
Sample thing i want to do 
Jenkins --> GCP CloudBuild -> Git Checkout Branch -> Docker Build ....

I can confirm the Git Login phase was success becuase i am able to list out the files , although i is wrong branch 

## Affected builder image
gcr.io/cloud-builders/git

## Expected Behavior
Switch context for select branch 

## Actual Behavior
Remain context in master branch

## Steps to Reproduce the Problem
```
            steps:
            # Access the id_github file from Secret Manager
            steps:
            - name: gcr.io/cloud-builders/gcloud
              entrypoint: 'bash'
              args: [ '-c', 'gcloud secrets versions access latest --secret=github-deploy-key > /root/.ssh/id_github' ]
              volumes:
              - name: 'ssh'
                path: /root/.ssh
            # Set up git with key and domain
            - name: 'gcr.io/cloud-builders/git'
              entrypoint: 'bash'
              args:
              - '-c'
              - |
                chmod 600 /root/.ssh/id_github
                cat <<EOF >/root/.ssh/config
                Hostname github.com
                IdentityFile /root/.ssh/id_github
                EOF
                ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
              volumes:
              - name: 'ssh'
                path: /root/.ssh
            # Connect to the repository
            - name: 'gcr.io/cloud-builders/git'
              args: ['clone','git@github.com:xyz/my_github_repo.git', '--branch', 'demo', '--single-branch']
              volumes:
              - name: 'ssh'
                path: /root/.ssh
            # Check Folder
            - name: bash
              args: ['ls', '-la']
              dir: 'my_github_repo'
            #Docker Build
            - name: 'gcr.io/cloud-builders/docker'
              args: ['build', '--tag=version_file', '.']
              dir: 'my_github_repo'         
```

## Additional Info
Also try add a phase 
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', '-b' ,'demo']

but same result .....
