### ISSUE TITLE
[BUG] gke-deploy cannot parse images from "eu.gcr.io" host

### ISSUE THREAD

**Issue by xunafay** [GoogleCloudPlatform/cloud-builders#739]
## Affected builder image

`gcr.io/cloud-builders/gke-deploy`

## Expected Behavior

can apply images from host `eu.gcr.io`

## Actual Behavior

Throws `Error: could not parse reference: "eu.gcr.io/personal-134286/portfolio:6ccad35"`

## Steps to Reproduce the Problem

1. Add gke-deploy step with an image from the eu host
```yml
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=config/deployment.yaml
  - --image=eu.gcr.io/${_CLOUDSDK_CONTAINER_PROJECT_ID}/${_IMAGE_NAME}:$SHORT_SHA
  - --location=${_CLOUDSDK_COMPUTE_ZONE}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
```
2. Run the cloud build

## Additional Info

after changing all references of `eu.gcr.io` to `gcr.io` the build works without additional changes
