### ISSUE TITLE
[BUG] Go builds with set GIT_CONFIG_VAL broken after #755

### ISSUE THREAD

**Issue by mlesar** [GoogleCloudPlatform/cloud-builders#759]
## Affected builder image

All images build after #755 merge.

## Expected Behavior

If `GIT_CONFIG_VAL` is set it should be used for fetching from private repositories.

## Actual Behavior

Currently, you get an error:
>fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by mlesar** [comment]
In our case, we use `GIT_CONFIG_VAL` to add the GitHub access token to the GitHub URL so that we can fetch data from private repositories.

Example:
```yaml
steps:
- name: gcr.io/cloud-builders/go:latest
  id: go-build
  args: ['build', '-o', 'service', 'main.go']
  env:
    - 'GIT_CONFIG_VAL=url."https://${_GITHUB_ACCESS_TOKEN}@github.com/".insteadOf "https://github.com/"'
    - 'GOPRIVATE=github.com/XXXX'
...
```
