### ISSUE TITLE
[FR] Examples With folders and secrets in documentation

### ISSUE THREAD

**Issue by rascontextual** [GoogleCloudPlatform/cloud-builders#761]
## Detailed Feature Information

I am trying to use the gs bucket as a secret in the Cloud Build pipeline, becuse my pipeline must sync the folder `tarea1` with de DAGS folder in cloud storage, but this does not work:

```steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gsutil', 'cp', '-R', 'dags/tarea1/', '$$gcp_bucket']
    secretEnv: ['gcp_bucket']
availableSecrets:
  secretManager:
  - versionName: projects/projectnumber/secrets/mysecret/versions/1
    env: 'gcp_bucket'
```
The  pipeline does not show any  fails, this is the output:

```gcr.io/google.com/cloudsdktool/cloud-sdk:latest
Copying file://dags/tarea1/subtarea1/dag.py...
/ [0 files][    0.0 B/  2.9 KiB]                                                
/ [1 files][  2.9 KiB/  2.9 KiB]                                                
Operation completed over 1 objects/2.9 KiB.                                      
PUSH
DONE
```

Could you explain how can we use Secrets and folders? Keep in git the bucket ID is not a good practice.

**Comment by jessieliu1** [comment]
Hi @rascontextual, thanks for the question! Secrets are available by using the bash entrypoint and -c in the build step. You can see details in the documentation [here](https://cloud.google.com/build/docs/securing-builds/use-secrets#configuring_builds_to_access_the_secret_from). 

Can you try something like the following:

```
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gsutil cp -R dags/tarea1/ $$gcp_bucket']
    secretEnv: ['gcp_bucket']
availableSecrets:
  secretManager:
  - versionName: projects/projectnumber/secrets/mysecret/versions/1
    env: 'gcp_bucket'
```
