### ISSUE TITLE
[BUG] Git revisions of master and HEAD are the same (after unshallow)

### ISSUE THREAD

**Issue by jredl-va** [GoogleCloudPlatform/cloud-builders#796]
We are currently in the process of moving one of our build processes back to google cloud build. However, we need a full git checkout. After doing so, the revision of HEAD and master are the same which is highly confusing. From the cloud build logs: 

```
Step #1 - "write-version": nx head revision: 9e6eaaf6a0836eb2857bf29dac339853bae5f8f3
Step #1 - "write-version": nx base revision: 9e6eaaf6a0836eb2857bf29dac339853bae5f8f3
```

The source repository is a google cloud source repository that is cloned from github. Here is the cloudbuild.yaml for reference:

```
steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # convert the shallow clone to regular one
        git fetch --unshallow
    id: 'fetch'

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # write the git revisions for the nx affected git comparison
        echo $(git rev-parse HEAD) > HEAD
        echo $(git rev-parse master) > BASE

        # write these revisions to the build log
        echo "nx head revision:" $(cat HEAD)
        echo "nx base revision:" $(cat BASE)
    id: 'write-version'
    waitFor: ['fetch']
```

If I was to update the the rev-parse command too:

```
        echo $(git rev-parse origin/master) > BASE
```

I then get the correct git revision for master?

## Affected builder image

`gcr.io/cloud-builders/git`

## Expected Behavior

I would expect the git revision of master to match that of master and not HEAD. Unless I'm crazy / uneducated on this topic and this is working as expected.
