### ISSUE TITLE
[BUG][Feature] - Docker -v can't mount local folder but volume only

### ISSUE THREAD

**Issue by Emixam23-FCMS** [GoogleCloudPlatform/cloud-builders#804]
## Affected builder image

`gcr.io/cloud-builders/docker`

## Expected Behavior

When running the following (using https://github.com/golang-migrate/migrate) from a cloud build yaml step definition:
```
docker run -v $$(pwd)/migrations:/migrations --network cloudbuild migrate/migrate -database "postgres://endpoint:1234/xxx&user=xx&password=xx" -path=/migrations/ up
```
I expect docker run to work (as it does in local on my Ubuntu machine)

## Actual Behavior

Cloud build says that I can't mount that given path that it contains invalid characters:
> ... invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed 

## Steps to Reproduce the Problem

Based on this, I need to do the following:

```
- name: gcr.io/cloud-builders/docker
    id: 'my-migration-step'
    entrypoint: '/bin/bash'
    volumes:
      - name: 'migrations'
        path: '/migrations'
    args:
      - '-c'
      - |
        cp $$(pwd)/migrations/* /migrations \
        && docker run -v migrations:/migrations --network cloudbuild migrate/migrate -database "postgres://endpoint:1234/xxx&user=xx&password=xx" -path=/migrations/ up
```

## Additional Info

If it's not a bug (but a misunderstanding on my end) can you explain why?

Thanks,

Max
