### ISSUE TITLE
[BUG] The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by chinmayabiswalMA** [GoogleCloudPlatform/cloud-builders#816]
## Affected builder image

gcr.io/cloud-builders/gke-deploy

Code below:
```
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Deploy Configmap'
    waitFor: ['Create Namespace', 'Update DB and Redis IPs']
    args:
    - run
    - --filename=path-to-configmap/my-configmap.yaml
    - --location=${_REGION}
    - --cluster=${_CLUSTER_NAME}
    - --project=${_MY_PROJECT_ID}
    - --output=configmap
```

## Expected Behavior
Deployed object with kind "ConfigMap" and name "my-configmap" is ready after 400ms

## Actual Behavior
4 times out of 10, the Cloud Build job fails with error below:
```
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Error: failed to apply deployment: failed to apply Secret configuration file with name "XXXXXXXXX" to cluster: failed to apply config from string: command to apply kubernetes config from string to cluster failed: exit status 1
```
## Steps to Reproduce the Problem

1. Create Kubernetes Auto Pilot cluster in GCP, with Private cluster enabled, Default SNAT enabled, Control plane global access disabled, VPC-native traffic routing enabled, Intranode visibility enabled, NodeLocal DNScache Enabled, HTTP Load Balancing enabled.
2. Setup a Cloud Build Job, with a step to deploy to the cluster. Sample below:
```
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Deploy Configmap'
    waitFor: ['Create Namespace', 'Update DB and Redis IPs']
    args:
    - run
    - --filename=path-to-configmap/my-configmap.yaml
    - --location=${_REGION}
    - --cluster=${_CLUSTER_NAME}
    - --project=${_MY_PROJECT_ID}
    - --output=configmap
```
As seen on the night of 27 Dec, the success rate has dropped to 28% of the build jobs triggered.

## Additional Info
1. Note that, this setup is working most of the time. The fact that it doesn't work some of the times is a head scratcher. Seems as if the Builder is trying to fetch the credentials to be able to connect to Kubernetes cluster. If that is so, this function has not been reliable.
