### ISSUE TITLE
Semantic release with google cloud CI/CD using git annotation tag

### ISSUE THREAD

**Issue by anandjaisy** [GoogleCloudPlatform/cloud-builders#838]
I am releasing the artifact to the Artifact registry in the Google cloud. I want to have a semantic versioning release cycle using the git annotation tag to the master branch.

```
steps:
  # This step show the version of Gradle
  - id: Gradle Install
    name: gradle:7.4.2-jdk17-alpine
    entrypoint: gradle
    args: ["--version"]

  # This step build the gradle application
  - id: Build
    name: gradle:7.4.2-jdk17-alpine
    entrypoint: gradle
    args: ["assemble"]

  - id: Publish
    name: gradle:7.4.2-jdk17-alpine
    entrypoint: "sh"
    args:
      - -c
      - |
        if [ $BRANCH_NAME == 'master' ]
        then
          echo "Branch is = $BRANCH_NAME"
          gradle publish
        fi
```

In the last publish step, I want to write a condition for finding the git tag for versioning like 1.0.0, similar to the other auto tools

**Now on TRAVIS CI/CD**
```

skip_cleanup: true
on:
    all_branches: false
    branch: master
    tag: true
    condition: "$TRAVIS_TAG = ~^v\d+\.\d+\.\d+$"
```

What is the equivalent of above semantic versioning release in GCP. How to write the regular expression condition on google cloud build
