### ISSUE TITLE
Where is the homevol mounted?

### ISSUE THREAD

**Issue by tsloughter** [GoogleCloudPlatform/cloud-builders#86]
I've been attempting to share a file written out during a step that builds a docker image and another step that uses it to tag the image. Similar to the `git` example in this repo.

I don't know where else to ask to find out what is going on. Based on the docs I would think writing out `./version` in one step would mean `./version` would exist in the next steps. That or that I could write to `/builder/home/version` and access that from later steps. But no matter what I've tried I find the file does not exist.

**Comment by tsloughter** [comment]
Or maybe the issue is that I'm doing the `$(cat version)` in the args list...

```
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: ['-c', 'docker tag us.gcr.io/$PROJECT_ID/$REPO_NAME:latest us.gcr.io/$PROJECT_ID/$REPO_NAME:$(cat version)']
```

Would I need to make a script to run instead?

**Comment by skelterjohn** [comment]
Writing to ./version and /builder/home/version should both work for persisting to the next step. 

Regarding $(cat version), you need to change that to $$(cat version). The single dollar refers to build substitutions, and $$ escapes it to be passed as a $ in the actual arg, which sh -c interprets.

**Comment by tsloughter** [comment]
Thanks! I actually still get `cat: version: No such file or directory` but I'll keep trying things if it is supposed to work :)

**Comment by skelterjohn** [comment]
Do you mind sending a minimal repro? If you have a config that looks like the following, I see file persistence in both of those directories.

```
steps:
- name: 'ubuntu'
  args: ['touch', './foo']
- name: 'ubuntu'
  args: ['touch', '/builder/home/foo']
- name: 'ubuntu'
  args: ['stat', './foo']
- name: 'ubuntu'
  args: ['stat', '/builder/home/foo']
```
