### ISSUE TITLE
[BUG] gke-deploy: Resources with the same name in different namespaces are marked as duplicate

### ISSUE THREAD

**Issue by jordangarrison** [GoogleCloudPlatform/cloud-builders#870]
## Affected builder image

`gcr.io/cloud-builders/gke-deploy`

## Expected Behavior

Previously, submitting a resource with the same name across 2 namespaces allowed for 2 resources to be created in the respective namespaces. This is the expected behavior and the behavior which occurs in `kubectl`

## Actual Behavior

When applying the manifest, such as the one shown below, it will only apply the last resource defined with a given name for a given kind.

```
WARNING: Deploying multiple objects share the same kind and name. Duplicate objects will be overridden:
{kind: Service, name: my-app}
```

## Steps to Reproduce the Problem

Apply the following resources with `gke-deploy` and `kubectl`. You will see `gke-deploy` will apply only the last resource while `kubectl` will create both in their respective namespaces.

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: my-app
    env: my-env
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: internal
spec:
  externalName: my-app.my-app.svc.cluster.local
  ports:
  - port: 3000
  type: ExternalName
```
