### ISSUE TITLE
Docker build squash

### ISSUE THREAD

**Issue by fabiosanger** [GoogleCloudPlatform/cloud-builders#897]
I would like to enable squash duriong build, but none of the workarounds available seem to do the trick, below is the current build

```
steps:
  - id: 'pull-experimental'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'pull', 'docker/dockerfile:1.5.2' ]
    env:
      - DOCKER_BUILDKIT=1
    # build the container image
  - id: 'build'
    waitFor: ['pull-experimental']
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      ['-c', 'docker build --squash --memory-swap=-1 -t eu.gcr.io/$PROJECT_ID/${_IMAGE_TAG} -f ${_IMAGE_NAME}/Dockerfile .']
    env:
      - DOCKER_BUILDKIT=1
```
